### ISSUE TITLE
Support Jekyll Templates

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#10]
GitHub Pages has built-in support for Jekyll. With https://www.npmjs.com/package/liquid we could support the templating language for Jekyll, all we'd need is a Parcel plugin that bundles these templates.

**Comment by davidnuescheler** [comment]
are you referring to turning the `helix-home` repo into website or is that a more general comment about helix as a project... as for turning helix-home into a somewhat reasonable website i think helix pages should do the trick.

eg.
https://helix-home-adobe.project-helix.page/hackathons/5-bsl.html?flush

**Comment by trieloff** [comment]
I'm referring to Helix in general, and filed it here, as it would affect multiple projects.
