### ISSUE TITLE
How does observation / indexing / query work

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#107]
It would be great to have an overview of the parts that make up indexing and how they interact.

## Intended Audience
- helix (core) developers

## contents

**Observation**
- onedrive
  - subscription
  - change-listener
- github
  - helix-bot
- google
  - ???

**indexing**
- index-files
- algolia

**query**
- using algolia directly
- static vs dynamic queries 
- using stored queries
- using dynamic queries

**questions**
- when I modify a document in onedrive, what happens so that it eventually ends up in the aloglia index?
- when I modify a document in github, what happens so that it eventually ends up in the aloglia index?
- when I modify a document in google docs, what happens so that it eventually ends up in the aloglia index?
- how does it know which index to use?
- what happens when I change the `fstab.yaml` ?
- what happens when I change the `helix-query.yaml` ?
- how do I setup indexing in a helix (proper) project?
- how do I setup indexing in a helix-pages project?

**Comment by tripodsan** [comment]
@dominique-pfister would you like to create a sequence diagram that shows the event flow in more detail?

**Comment by dominique-pfister** [comment]
sure :-) any tool you could recommend?
