### ISSUE TITLE
DevOps: Helix Actions Management 

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#109]
With the current setup, helix has many actions, some used for delivery, some for publishing and deployment. DevOps is currently lacking a tool to manage the set of active actions, know their last known-good state and have the ability to revert to a prior state quickly.

the current rate of updates and redeployment of actions, it is only a matter of time, until due to a bad dependency update, several broken actions get redeployed. the devops on-call would have a hard time to relink all the broken actions.

as a DevOps (on call), I would like to have a tool that:
- shows the current set of a active actions (sequence links, eg v1 -> 1.3.1)
- shows a history of the action version
- (knows which versions are actually in use)
- allows to re-link the action versions to a prior/different state
- ideally I can do all of the above using a GUI

additional features:
- find which actions use which npm packages (#94)
- delete unused actions

**Comment by rofe** [comment]
I could see both a GUI and a CLI come in handy.

**Comment by trieloff** [comment]
See also the discussion in https://github.com/adobe-private/project-helix/issues/401

**Comment by kptdobe** [comment]
Shouldn't that be a contribution to Openwhisk ?

**Comment by tripodsan** [comment]
> Shouldn't that be a contribution to Openwhisk ?

eventually....maybe... but the teams have different approaches when it comes to versioning.

**Comment by tripodsan** [comment]
implemented: https://app.project-helix.io/admin/#/
