### ISSUE TITLE
context.request.selector not available in production deployment

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-home#114]
**Description**
I did not yet identified in which layer this should be fixed, thus creating the issue here for now.
`context.request.selector` is not filled in production.

**To Reproduce**
1. Create a project
2. Create `myselector_html.htl` and `myselector_html.pre.js` files
3. In `myselector_html.pre.js` output the selector value: `logger.info('selector from pre.js:'+ context.request.selector);`
4. Run `hlx up` and request a page like `http://localhost:3000/README.myselector.html`
-> check the logs, you can see a line like `selector from pre.js: myselector`
5. Run `hlx deploy; hlx publish`
6. Request the same page from Fastly
-> check the activation logs of the corresponding action (`<namespace>/myselector_html`), line is: `selector from pre.js: `

**Expected behavior**
Logs should output the same than locally: `selector from pre.js: myselector`

**Version:**
run: `$ hlx --version`
8.1.10

**Comment by tripodsan** [comment]
not needed anymore for helix 3
