### ISSUE TITLE
Update GitHub Secrets through CircleCI

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#119]
We have two bots that somewhat require a GitHub token:
- @tripodsan's auto-commit bot that touches each branch, so that renovatebot's commits get access to the CircleCI context
- @trieloff's semantic-commit comment bot that leaves many comments if it is using the built-in `GITHUB_TOKEN`, but only one if you provide it with one

So far, setting up the token as a secret for the repository has been a manual process, which means it's done inconsistently and frequently not at all.

But, there is an automated solution: GitHub has a [Secrets API](https://developer.github.com/v3/actions/secrets/) so we can write the secret and take it out of the CircleCI context. Encoding the secret requires some JS code: https://developer.github.com/v3/actions/secrets/#example-encrypting-a-secret-using-nodejs

**Comment by tripodsan** [comment]
> * @trieloff's semantic-commit comment bot that leaves many comments if it is using the built-in `GITHUB_TOKEN`, but only one if you provide it with one

the semantic comment bot doesn't need a token. we can use the one from github actions.

(also, in case you missed: I moved _your_ action to https://github.com/adobe-rnd/github-semantic-release-comment-action)

**Comment by trieloff** [comment]
I found that my action behaves differently when used with a non-built-in token: it is able to update an existing comment. That might be the extra convenience we need.

**Comment by trieloff** [comment]
Also, can you give me permissions on the `adobe-rnd` fork of my action? I'd like to add some tags.

**Comment by tripodsan** [comment]
> I found that my action behaves differently when used with a non-built-in token: it is able to update an existing comment. That might be the extra convenience we need.

I think you missed this one too:
https://github.com/adobe-rnd/github-semantic-release-comment-action/commit/fa348d1fb6d28b7d856f8ee00dc7ab6939802ee8

I fixed it in a way, so that it updates the existing commit, based on a marker and not based on the user.
