### ISSUE TITLE
Watchers for content repositories

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#12]
Helix should allow users to register repository watchers, so that actions can be performed in response to changes in the content repository. Actions can be project specific (code resides in the `code` repository) or global (any URL that accepts the right kind of POST requests).

Examples for actions:
- invalidate cache
- check for broken links
- trigger Adobe I/O events

I see following steps to implementation:

## In `strains.yaml`
- add a new key `watchers` (array)
- each entry is a string (URL or file name of a `js` file in the current repo)

## In `hlx deploy`

- each `js` file referenced by `watchers` gets packaged and deployed as an action to OpenWhisk
- for each `js` file, the exported `filters` method is called and the response is kept
- for each URL, a GET request (Accept `application/json`) is made and the response (if it is a JSON object) is kept
- the file `src/openwhisk/webhook.js` gets deployed at `hlx--webhook`. All `filter` responses collected in the above steps are passed as a `filters` default parameter
- the action `hlx-webhook` is registered as a webhook for all `push` events in all `content` repositories mentioned in `strains.yaml`

## In `webhook.js`

The webhook handler will only take care of converting `push` events into lists of changed files and dispatch new events to each watcher when the configured filters match. It is only concerned with GitHub semantics and won't try to parse markdown or interpret the changed files in any way.

- receive the `PushEvent` [payload looks like this](https://developer.github.com/v3/activity/events/types/#pushevent)
- for each `commit`, in `commits`, get the list of changed `files` from the [commit REST API](https://developer.github.com/v3/repos/commits/#get-a-single-commit)
- for each `filter` and `file` compare if the `allow` and `deny` expressions for `repo`, `owner`, `ref`, `path`, `dirname` ,`extension`, `author`, `committer` match
- if yes, and the file is not a binary, fetch the raw file
- then POST a combined payload (push event, commit JSON, raw text) to the configured URL

## Authentication considerations

- `hlx deploy` needs a token to write the repo
- `hlx--webhook` needs read access

----

This way, each action can configure which events it wants to receive in advance.

**Comment by trieloff** [comment]
done.

**Comment by tripodsan** [comment]
we can use openwhisk triggers for this:

1. when helix bot is added to a content repository, it creates a [trigger](https://github.com/apache/openwhisk/blob/master/docs/triggers_rules.md) in the customers namespace named `{owner}--{repo}--{ref}`.
2. when a modification occurs, the helix bot filters them according to some white/blacklists, and then fires the trigger with a payload of the list of modified resources.
3. a customer wishes to get notified, can install a openwhisk rule for that trigger to their action.
4. (accordingly, it could instrument the onedrive/googledocs change listener to do the same)

**Comment by tripodsan** [comment]
closing won't fix. reconsider later.
