### ISSUE TITLE
New Repo: helix-ow-cache

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#123]
Create a new repository with the name `helix-ow-cache`:

> A caching library for optimized for `ow.action.invoke` that supports timeout-based caching, stale serving, and cache headers in web actions.

## Stuff you can do yourself

- [ ] run `npm init @adobe/helix-library` or `npm init @adobe/helix-service`
- [ ] Add topics to the repository, at least `helix`
- [ ] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [ ] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [ ] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [ ] Set the repository description
- [ ] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference. (*skip for libraries*)
- [ ] Prepare setup of OrgProjectBot
  - [ ] Add a [`.github/org-project-bot.yaml`](https://github.com/adobe/helix-cli/blob/master/.github/org-project-bot.yaml)
- [ ] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
- [ ] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

## Stuff you need an Adobe Org Admin for
- [ ] Enable [OrgProjectBot](https://github.com/organizations/adobe/settings/installations/690408)
- [ ] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)

**Comment by tripodsan** [comment]
can we try this first in helix-dispatch before creating a full-fledged library?

**Comment by trieloff** [comment]
I wanted to try it in Helix-Content-Proxy, too, so I thought a separate library would be better. I can bootstrap it in my personal repo if you are worried that we might end up with an instant deprecation.

**Comment by trieloff** [comment]
Nevermind, `helix-shared` is probably a good place for this.
