### ISSUE TITLE
Standardize headers containing original host

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#126]
## Overview
We are using several different headers to track the original URL or host name across different requests in the Helix chain. Some of them are custom headers we set in Fastly. I think we would benefit from using standard headers instead in order to support other CDNs like Cloudflare.

## Details
- In https://github.com/adobe/helix-pages/issues/118, we introduced a new custom header `x-hlx-pages-host` for the sitemap.xml.
- Later in #70 we decided to introduce a new custom header `x-cdn-url` which is being forwarded from Fastly all the way down to actions called by dispatch, facilitating the tracking of requests through the system.

## Proposed Actions
We should consider replacing these custom headers with the standard header`x-forwarded-host`.

See also @davidnuescheler's comment here: https://github.com/adobe/helix-pages/issues/284#issuecomment-634779047

**Comment by trieloff** [comment]
I think the issue with `X-Forwarded-Host` is that Adobe I/O Runtime always overwrites it. So it can be anything, but `X-Forwarded-Host`.

**Comment by trieloff** [comment]
See also: https://github.com/adobe/helix-publish/issues/451
