### ISSUE TITLE
enable markup diff testing

### ISSUE THREAD

**Issue by MarquiseRosier** [adobe/helix-home#127]
**Is your feature request related to a problem? Please describe.**
currently there is no way to compare live pages across changes to services; something that helix by design makes easy. As mentioned by @tripodsan a change to word2md, gdoc2md, embed, data-embed and more can cause changes in the markup that we should catch before updating a service. 

**Describe the solution you'd like**
After a discussion with @davidnuescheler just comparing Markup seems to be the better solution here; because he noted that "all the problems with markup didn't impact the layout
for example the ```<meta> & <link> ``` tags..." 

**Describe alternatives you've considered**
image comparison between rendered pages; but this only solves layout issues; which if caused by markup changes unwittingly caused by service updates, can be detected purely with markup comparison. 
 
**Additional context**
Currently, awaiting development of https://github.com/adobe/helix-home/issues/125

**Comment by tripodsan** [comment]
I don't think that this is enough. there are also a lot of transformations done to the markdown and dom in the pipeline and pre.js. 

anyways, once we have the content-proxy, we can do diff testing on those resources.

**Comment by MarquiseRosier** [comment]
helix-shared has a resource for markup diffs

**Comment by kptdobe** [comment]
As discussed @MarquiseRosier, here is a bit of context to add some simple diff testing to existing tests:
- https://github.com/adobe/helix-pages/blob/master/.circleci/config.yml#L259-L287 defines the list of tests that run when a commit is coming in a branch of helix-pages
- each test defines a repo and a script to execute to run those tests
- helix-pages will run those tests by giving them the test domain they need to run against (the test domain is where WIP version of helix-pages is being deployed)
- one example: you can find a list of those tests: https://github.com/adobe/theblog-tests/tree/master/test/smoke
- one of them is https://github.com/adobe/theblog-tests/blob/master/test/smoke/test.generic.structure.output.js - it tests some of the DOM elements of 2 pages (homepage and introducing-public-beta.html).
- as a first step, I would add a new test here: make a diff between `https://theblog-adobe.${testDomain}/...` and the same page on `https://theblog-adobe.hlx.page/` - ideally, the DOM should be the same.

**Comment by tripodsan** [comment]
I think this is more or less in place.
