### ISSUE TITLE
Improve Status Monitoring for Adobe I/O Runtime

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#13]
When you check https://status.project-helix.io, it appears that Adobe I/O Runtime is 100% available, while the services running on top of it have lower availability.

This is an artifact of our monitoring setup. For all Helix Services, we execute an action on Adobe I/O Runtime, whereas for Adobe I/O Runtime itself, we only access the API root resource, which is cached and served through Adobe I/O API Gateway. 

I'd suggest we create an additional `helix-runtime-monitoring` service that is deployed with all other Helix Services in the `helix` namespace, but serves as a monitoring probe for Adobe I/O Runtime.

**Comment by rofe** [comment]
We can use `helix-status` as a monitoring probe for Runtime. All we need to do is rewire it to the Runtime component in Statuspage, and probably also remove it from the Delivery container policy in New Relic.
