### ISSUE TITLE
Create new private repository for helix-task-support

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-home#133]
Create a new **private** repository with the name `helix-task-support`
Related to #129 

## Stuff you can do yourself

- [x] run `npm init @adobe/helix-library` or `npm init @adobe/helix-service`
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [x] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [x] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference. (*skip for libraries*)
- [x] Prepare setup of OrgProjectBot
  - [x] Add a [`.github/org-project-bot.yaml`](https://github.com/adobe/helix-cli/blob/master/.github/org-project-bot.yaml)
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

## Stuff you need an Adobe Org Admin for
- [x] Enable [OrgProjectBot](https://github.com/organizations/adobe/settings/installations/690408)
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)

**Comment by tripodsan** [comment]
@trieloff @stefan-guggisberg @kptdobe  can you help?

**Comment by stefan-guggisberg** [comment]
i'll take a stab

**Comment by trieloff** [comment]
![helix-task-support](https://user-images.githubusercontent.com/39613/84008290-ecf37c00-a971-11ea-801f-fa80c8cb899b.png)

**Comment by stefan-guggisberg** [comment]
* created a bare repo: https://github.com/adobe/helix-task-support
* set permissions
* enabled OrgProjectBot & Renovatebot

**Comment by dominique-pfister** [comment]
Hm, in https://app.circleci.com/pipelines/github/adobe/helix-task-support/4/workflows/297a1eff-c818-4adf-9cd2-1e2dfe114a9d/jobs/7 circleci says:
```
[@semantic-release/npm] › ℹ  Published @adobe/helix-task-support@1.0.0 to dist-tag @latest on https://registry.npmjs.org/
```
But when trying to `npm install` that library, it says:
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@adobe%2fhelix-task-support - Not found
```
Any clues?

**Comment by stefan-guggisberg** [comment]
The package scope was private. I fixed it. It should work now.

**Comment by tripodsan** [comment]
> The package access level was `restricted`, see https://docs.npmjs.com/cli-commands/access.html#details.
> 
> I fixed it. It should work now.

let's keep it private for now... I will remove the published releases again.

**Comment by tripodsan** [comment]
> 
> But when trying to `npm install` that library, it says:
> 
> ```
> npm ERR! 404 Not Found - GET https://registry.npmjs.org/@adobe%2fhelix-task-support - Not found
> ```
> 
> Any clues?

@dominique-pfister you need to authenticate with your npm auth, in order to be able to install the private packages.

you are in the list of maintainers, so you should have access.

just add the token to your `.npmrc`:

```
//registry.npmjs.org/:_authToken=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
