### ISSUE TITLE
Document Helix Cookies

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#14]
For compliance reasons, we need a public documentation where we list all cookies Helix is issuing, what they contain and what they are used for.

**Comment by tripodsan** [comment]
currently that’s simple: no cookies :-)
except during`hlx auth`

**Comment by rofe** [comment]
@trieloff mentioned a strain cookie, but I don't know under which circumstances it is set.

**Comment by trieloff** [comment]
There is an `X-Strain` cookie, which gets set for "sticky" strains, i.e. strains which have a condition that can only be evaluated on the very first request. It is a same-site, HTTPS-only session-cookie that contains no PII.

**Comment by rofe** [comment]
Not relevant for Helix 3.
