### ISSUE TITLE
Rename branch "master" to "main"

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-home#140]
Adobe Engineering Council decided that `master` branch should be renamed to `main`. 
2 main operations are required to be performed for each of our repos:
- create the `main` branch, make it the default branch and delete the `master` branch. See [here](https://dev.to/rhymu8354/git-renaming-the-master-branch-137b) for easy step-by-step instructions. 
- in the code, search and replace all occurrences of `master` by `main`, at least when `master` refers to a branch name (which is often the case in Helix since we use the `master` branch as default to find content and code during rendering).

Here is a query to find all `master` occurrences (~~532 546~~ 509) in our code: https://github.com/search?q=master+repo%3Aadobe%2Fgit-server+repo%3Aadobe%2Fhtlengine+repo%3Aadobe%2Fhelix-pipeline+repo%3Aadobe%2Fhelix-cli+repo%3Aadobe%2Fhelix-home+repo%3Aadobe%2Fproject-helix.io+repo%3Aadobe%2Fhelix-vulcain-filters+repo%3Aadobe%2Fhelix-publish+repo%3Aadobe%2Fvscode-helix+repo%3Aadobe%2Fparcel-plugin-htl+repo%3Aadobe%2Fhelix-shared+repo%3Aadobe%2Fhelix-embed+repo%3Aadobe%2Fhelix-simulator+repo%3Aadobe%2Fhelix-fetch+repo%3Aadobe%2Ftheblog+repo%3Aadobe%2Fhelix-pages+repo%3Aadobe%2Fopenwhisk-action-builder+repo%3Aadobe%2Fhelix-helpx+repo%3Aadobe%2Fparcel-plugin-jst+repo%3Aadobe%2Fopenwhisk-loggly-wrapper+repo%3Aadobe%2Fhelix-data-embed+repo%3Aadobe%2Fhelix-static+repo%3Aadobe%2Fhelix-dispatch+repo%3Aadobe%2Fhelix-run-query+repo%3Aadobe%2Fhelix-logging+repo%3Aadobe%2Fhelix-dockerimage+repo%3Aadobe%2Fhelix-perf+repo%3Aadobe%2Fhelix-ops+repo%3Aadobe%2Fprobot-serverless-openwhisk+repo%3Aadobe%2Fhelix-qr-code+repo%3Aadobe%2Fopenwhisk-action-utils+repo%3Aadobe%2Fhelix-service+repo%3Aadobe%2Fhelix-log+repo%3Aadobe%2Fhelix-library+repo%3Aadobe%2Fhelix-continuous+repo%3Aadobe%2Fhelix-status+repo%3Aadobe%2Fhelix-index-pipelines+repo%3Aadobe%2Fhelix-index-files+repo%3Aadobe%2Fhelix-testutils+repo%3Aadobe%2Fopenwhisk-action-logger+repo%3Aadobe%2Fhelix-query-index+repo%3Aadobe%2Fopenwhisk-probot-builder+repo%3Aadobe%2Ftheblog-tests+repo%3Aadobe%2Fhelix-redirect+repo%3Aadobe%2Fhelix-param-checker+repo%3Aadobe%2Fhelix-content-proxy+repo%3Aadobe%2Fhelix-example-advanced+repo%3Aadobe%2Fhelix-eslint-config+repo%3Aadobe%2Fhelix-auth-fastly+repo%3Aadobe%2Fhelix-index-big-tree+repo%3Aadobe%2Fhelix-resolve-git-ref+repo%3Aadobe%2Fhelix-example-basic+repo%3Aadobe%2Fhelix-querybuilder+repo%3Aadobe%2Fhelix-index-tree+repo%3Aadobe%2Fhelix-cache-flush+repo%3Aadobe%2Fhelix-onedrive-support&type=Code

**Comment by stefan-guggisberg** [comment]
- [x] https://github.com/adobe/git-server/issues/210

**Comment by trieloff** [comment]
We can rename our branches to main right away,  but changing the assumption that the default branch is main will break things (for all customer repos that have been created before GitHub changed the defaults). Isn't there a way to determine the default branch name in GitHub?

**Comment by kptdobe** [comment]
Correct, we have to be careful with the "code" part of the work: we'll have to support for a certain time 2 potential default branch name: `master` and `main`.
GitHub said they will change the default default branch to `main` thus at one point, new customer repos will come with `main`. Once GitHub makes the change, if we drop `master`, we break backward comp (2 options then: either we migrate all existing customer repos or we support both).

https://developer.github.com/v3/repos/#get-a-repository gives the `default_branch`.

**Comment by tripodsan** [comment]
supporting both will be a bit tricky, since the fallback to master is at many places. like in the VCL, when the first part of a helix pages project is missing. we should probably remove all fallbacks and try to default as late as possible. maybe resolve-git-ref can figure out the default automatically? @stefan-guggisberg  ?

**Comment by stefan-guggisberg** [comment]
@tripodsan I created an issue: adobe/helix-resolve-git-ref#253

**Comment by tripodsan** [comment]
see https://github.com/github/renaming

**Comment by rofe** [comment]
I changed the `helix-home` default branch to `main`, but left the `master` branch for now because Helix Pages still expects it when no branch is specified in the URL, e.g. https://helix-home--adobe.hlx.page/getting-started.html

**Comment by dominique-pfister** [comment]
- [x] helix-onedrive-cli
- [x] helix-onedrive-listener
- [x] helix-onedrive-support
- [x] helix-index-files
- [x] helix-index-pipelines
- [x] helix-observation-cli
- [x] helix-param-checker
- [x] helix-task-support
- [x] helix-task-worker
- [x] helix-task-controller

**Comment by rofe** [comment]
So cool! Thanks @dominique-pfister

**Comment by tripodsan** [comment]
updated list:

- [x] [fastly-native-promises](https://github.com/adobe/fastly-native-promises)
- [x] [htlengine](https://github.com/adobe/htlengine)
- [x] [helix-pipeline](https://github.com/adobe/helix-pipeline)
- [x] [helix-cli](https://github.com/adobe/helix-cli)
- [x] [git-server](https://github.com/adobe/git-server)
- [x] [helix-simulator](https://github.com/adobe/helix-simulator)
- [x] [probot-serverless-openwhisk](https://github.com/adobe/probot-serverless-openwhisk)
- [x] [project-helix.io](https://github.com/adobe/project-helix.io)
- [x] [helix-bot](https://github.com/adobe/helix-bot)
- [ ] [vscode-helix](https://github.com/adobe/vscode-helix)
- [x] [helix-library](https://github.com/adobe/helix-library)
- [x] [helix-shared](https://github.com/adobe/helix-shared)
- [ ] [helix-embed](https://github.com/adobe/helix-embed)
- [ ] [helix-logging](https://github.com/adobe/helix-logging)
- [x] [helix-publish](https://github.com/adobe/helix-publish)
- [ ] [helix-perf](https://github.com/adobe/helix-perf)
- [ ] [helix-testutils](https://github.com/adobe/helix-testutils)
- [x] [openwhisk-action-builder](https://github.com/adobe/openwhisk-action-builder)
- [ ] [helix-ctl](https://github.com/adobe/helix-ctl)
- [ ] [helix-bot-action-mail-sink](https://github.com/adobe/helix-bot-action-mail-sink)
- [ ] [helix-bot-action-login](https://github.com/adobe/helix-bot-action-login)
- [ ] [helix-bot-action-config](https://github.com/adobe/helix-bot-action-config)
- [ ] [helix-pages](https://github.com/adobe/helix-pages)
- [ ] [helix-static](https://github.com/adobe/helix-static)
- [x] [helix-service](https://github.com/adobe/helix-service)
- [x] [helix-dispatch](https://github.com/adobe/helix-dispatch)
- [x] [helix-resolve-git-ref](https://github.com/adobe/helix-resolve-git-ref)
- [x] [helix-status](https://github.com/adobe/helix-status)
- [ ] [helix-bot-shared](https://github.com/adobe/helix-bot-shared)
- [ ] [helix-log](https://github.com/adobe/helix-log)
- [x] [helix-eslint-config](https://github.com/adobe/helix-eslint-config)
- [x] [openwhisk-action-utils](https://github.com/adobe/openwhisk-action-utils)
- [x] [openwhisk-probot-builder](https://github.com/adobe/openwhisk-probot-builder)
- [ ] [helix-bot-action-dns](https://github.com/adobe/helix-bot-action-dns)
- [x] [helix-gdocs2md](https://github.com/adobe/helix-gdocs2md)
- [ ] [helix-index-tree](https://github.com/adobe/helix-index-tree)
- [x] [helix-index-files](https://github.com/adobe/helix-index-files)
- [x] [helix-index-pipelines](https://github.com/adobe/helix-index-pipelines)
- [ ] [helix-run-query](https://github.com/adobe/helix-run-query)
- [x] [helix-word2md](https://github.com/adobe/helix-word2md)
- [ ] [helix-index-big-tree](https://github.com/adobe/helix-index-big-tree)
- [x] [helix-vulcain-filters](https://github.com/adobe/helix-vulcain-filters)
- [x] [helix-ops](https://github.com/adobe/helix-ops)
- [ ] [helix-auth-fastly](https://github.com/adobe/helix-auth-fastly)
- [x] [openwhisk-action-logger](https://github.com/adobe/openwhisk-action-logger)
- [x] [helix-fetch](https://github.com/adobe/helix-fetch)
- [x] [helix-onedrive-listener](https://github.com/adobe/helix-onedrive-listener)
- [x] [helix-onedrive-support](https://github.com/adobe/helix-onedrive-support)
- [x] [helix-epsagon](https://github.com/adobe/helix-epsagon)
- [ ] [helix-bulk-editor](https://github.com/adobe/helix-bulk-editor)
- [x] [helix-onedrive-cli](https://github.com/adobe/helix-onedrive-cli)
- [ ] [helix-query-index](https://github.com/adobe/helix-query-index)
- [x] [helix-param-checker](https://github.com/adobe/helix-param-checker)
- [ ] [helix-observation](https://github.com/adobe/helix-observation)
- [ ] [helix-observation-admin](https://github.com/adobe/helix-observation-admin)
- [ ] [helix-data-embed](https://github.com/adobe/helix-data-embed)
- [x] [helix-qr-code](https://github.com/adobe/helix-qr-code)
- [ ] [helix-action-admin](https://github.com/adobe/helix-action-admin)
- [x] [helix-content-proxy](https://github.com/adobe/helix-content-proxy)
- [x] [helix-documents-support](https://github.com/adobe/helix-documents-support)
- [ ] [helix-redirect](https://github.com/adobe/helix-redirect)
- [x] [helix-task-controller](https://github.com/adobe/helix-task-controller)
- [x] [helix-task-worker](https://github.com/adobe/helix-task-worker)
- [x] [helix-observation-cli](https://github.com/adobe/helix-observation-cli)
- [x] [helix-task-support](https://github.com/adobe/helix-task-support)
- [ ] [helix-querybuilder](https://github.com/adobe/helix-querybuilder)
- [ ] [helix-cache-flush](https://github.com/adobe/helix-cache-flush)
- [ ] [helix-gdrive-listener](https://github.com/adobe/helix-gdrive-listener)
- [x] [helix-purge](https://github.com/adobe/helix-purge)
- [x] [helix-excel-indexer](https://github.com/adobe/helix-excel-indexer)
- [x] [helix-slack-bot](https://github.com/adobe/helix-slack-bot)
- [x] [helix-markdown-support](https://github.com/adobe/helix-markdown-support)
- [x] [helix-version-picker](https://github.com/adobe/helix-version-picker)

**Comment by tripodsan** [comment]
closing - helix-pages is the last one, which will we can rename, once helix2 doesn't need it anymore.
