### ISSUE TITLE
Add preview button for (online) word and google docs

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#141]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a way to open the browser at the correct location to preview the current document an author is editing.

### approach
- add functionality to content-proxy to resolve a document link to the external url of the document url
- the action would return a redirect (302) to the respective location
- create a bookmarklet that opens a new browser window with the respective action url

**Comment by tripodsan** [comment]
initial bookmarklet creator:

https://www.project-helix.io/doc/general/preview-bookmarklet.html?a=2

**Comment by trieloff** [comment]
A couple more ideas how we could make previews easier:

- Message the author on Slack/MS Teams
- add a review comment to the document
- send an email
