### ISSUE TITLE
Preview bookmarklet chokes on "shared" SharePoint URLs

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#144]
**Description**
When trying to use the Preview button on a document which has been opened using a OneDrive share link, the result is `not found`.

**To Reproduce**
1. Go to https://adobe.sharepoint.com/:w:/s/TheBlog/Edr7ds2IshdIhB3nYhw2u7oBhBW2ZbwBdevimlM2zu9XUw?email=rofe%40adobe.com&e=4%3A4vbvu8&at=9&wdLOR=c4B1C6710-5115-6545-A284-0CE79B7C7B68
2. Click on Preview
3. Get stuck on https://adobeioruntime.net/api/v1/web/helix/helix-services/content-proxy@v1?owner=adobe&repo=theblog&ref=master&path=%2F&lookup=https%3A%2F%2Fadobe.sharepoint.com%2F%3Aw%3A%2Fs%2FTheBlog%2FEdr7ds2IshdIhB3nYhw2u7oBhBW2ZbwBdevimlM2zu9XUw%3Femail%3Drofe%2540adobe.com%26e%3D4%253A4vbvu8%26at%3D9%26wdLOR%3Dc4B1C6710-5115-6545-A284-0CE79B7C7B68
4. Go to https://adobe.sharepoint.com/:w:/r/sites/TheBlog/_layouts/15/Doc.aspx?sourcedoc=%7BCD76FBDA-B288-4817-841D-E7621C36BBBA%7D&file=which-product-do-i-use-to-create-that.docx&action=default&mobileredirect=true
5. Click on Preview
6. Correctly end up on https://theblog--adobe.hlx.page/en/publish/2017/07/18/which-product-do-i-use-to-create-that.html

**Expected behavior**
Preview button always opens the correct URL.

**Additional context**
#141

**Comment by tripodsan** [comment]
when I open the link above, I get redirect to:
https://adobe.sharepoint.com/:w:/r/sites/TheBlog/_layouts/15/guestaccess.aspx?email=rofe%40adobe.com&e=4%3A4vbvu8&at=9&wdLOR=c4B1C6710-5115-6545-A284-0CE79B7C7B68&share=Edr7ds2IshdIhB3nYhw2u7oBhBW2ZbwBdevimlM2zu9XUw

how did you create that link ?

**Comment by rofe** [comment]
I got it by following a link in an email SharePoint sent me on behalf of the sharer ("someone shared xyz with you"). I just looked it up again and copied the original link from the email:
https://adobe.sharepoint.com/:w:/s/TheBlog/Edr7ds2IshdIhB3nYhw2u7oBhBW2ZbwBdevimlM2zu9XUw?email=rofe%40adobe.com&e=4%3a4vbvu8&at=9 
Preview doesn't work on this URL either.

**Comment by tripodsan** [comment]
when I click on the link, I get:

![image](https://user-images.githubusercontent.com/917628/89754146-bb379680-db15-11ea-819e-9e054e68179a.png)

and then I land on the resolved link above (the one with /sites/)

**Comment by tripodsan** [comment]
in any case, the preview redirect doesn't work.... I think the sharepoint doc id cannot be retrieved.
maybe we can do something with this id: `c4B1C6710-5115-6545-A284-0CE79B7C7B68` .... need to look into it.

**Comment by rofe** [comment]
> when I click on the link, I get...

Because it has been shared with me :) I can share it with you (I'm guessing you can't share it with yourself) so you'll get a link you can open.

**Comment by rofe** [comment]
@tripodsan do you have any update on this?

**Comment by tripodsan** [comment]
no... no supported :-)
