### ISSUE TITLE
HLXPURGE

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#145]
## Overview
The FASTLYPURGE method of purging something from the outer CDN got me thinking. What if we had a HLXPURGE method that can purge both inner and outer CDN.

## How to build it

1. adobe/helix-publish#569
2. in helix-publish, intercept the HLXPURGE method and forward the current URL and the XFH header (we can deduct outer CDN URL from that) to a new helix-purge action
3. helix-purge purges the inner CDN with a surrogate key
4. helix-purge purges the outer CDN using the PURGE method
5. everyone's happy

## Proposed Actions

Do it?

**Comment by tripodsan** [comment]
we already have this in place, using the cache-flush-action.... so the helix-publish can directly invoke it.

does runtime allow custom http method names?

**Comment by trieloff** [comment]
even if it does not, we can change the method in vcl

**Comment by tripodsan** [comment]
> even if it does not, we can change the method in vcl. 

ok

> So we adjust cache-flush to take the forwarded request, too

it needs repo/owner/ref, the original document path + mountpoint (or the correct source-location). currently it is only invoked via observation, which generates a change event. eg:

```
{
  "owner": "adobe",
  "repo": "theblog",
  "ref": "master",
  "observation": {
    "provider": {
      "driveId": "b!PpnkewKFAEaDTS6slvlVjh_3ih9lhEZMgYWwps6bPIWZMmLU5xGqS4uES8kIQZbH"
    },
    "type": "onedrive",
    "change": {
      "uid": "uJoyhgL7Iyii3HtM",
      "path": "/theblog/en/query-index.xlsx",
      "time": "2020-07-01T10:22:18Z",
      "type": "modified",
      "provider": {
        "itemId": "01DJQLOWZ2NO76OI7TOZAJNCZQUFLF6I3T"
      }
    },
    "mountpoint": {
      "path": "/",
      "root": "/"
    }
  }
}
```

but this is only needed to calculate the surrogate key. I guess, if we can call it with a `source-location`, it should work if https://github.com/adobe/helix-publish/issues/569 is implemented. (so nobody needs to resolve the onedrive item again :-)

**Comment by tripodsan** [comment]
I created https://github.com/adobe/helix-cache-flush/issues/40
