### ISSUE TITLE
Give me more control over embed markup, but don't break compatibility

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#148]
## Overview

For the blog we'd like to have the option to replace the server-side (external) embeds with client-side embeds, so that we can defer loading them until users interact with the media. Ideally, this would be a solution that works with helix pages, so that project-specific solutions are possible, but does not break compatibility.

## Possible Approaches

TBD

**Comment by tripodsan** [comment]
closing as won'r fix in helix 3.
