### ISSUE TITLE
How to (or why not to) post-process HTML in Helix

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#15]
From @ryanbetts:

> Just hopped in here to field a general question about Helix’s mechanics that I’m still struggling to wrap my head around. I’ve read through the Anatomy of the Pipeline, which was helpful, and just saw @bdelacre’s “How Helix Works” initial draft. Both of these provide some useful context. Where it falls apart for me still is:

> It’s clear how an individual set of files are woven together to build a piece of the final page to be delivered to a person’s device (eg. global nav, the content of an individual page, a blog component on that page, the global footer). I know how to pre and post process those individual elements/templates/partials using the Helix Pipeline.

> That said, I still have an instinct to want to post-process the assembled final result for certain things, before it is cached for the client. For example, if the same SVG icon has been inlined in all 4 of the above mentioned templates, I’d want to analyze the final HTML and strip it down to a single resource. This seems to be a Helix anti-pattern – or just not possible do to other than on the client side.

> Am I correct in that understanding? If so, would love to know what the better approach is. I’m still new to serverless, Fastly and VCL. My assumption is that’s where the gap in understanding lies for me.

**Comment by tripodsan** [comment]
closing for now, as we don't support post process anymore in helix 3.
