### ISSUE TITLE
429 from Sharepoint propagated as 404

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#150]
Somewhere in the content-proxy, pipeline, dispatch chain, a 429 gets turned into a 404, which may get cached by the outer cdn. Propagate it properly and we can cache the 429 in the outer cdn for a short time only.

@stefan-guggisberg

**Comment by trieloff** [comment]
https://helix.coralogix.com/#/query/logs?id=2tQO9j8YZWy

**Comment by tripodsan** [comment]
hmm...it seems that this test is the same as the one above:
https://github.com/adobe/helix-dispatch/blob/b8982b86e79d8201a36c106767d0709ad7e5f412/test/index.test.js#L510

IIRC, the idea was to test what happens if a `/404.html` returns a 429.

**Comment by tripodsan** [comment]
the utility in helix-shared turns it to a 503:

https://github.com/adobe/helix-shared/blob/2d87824491728a6343030613a081f107e47ab9b1/src/utils.js#L22-L37

**Comment by stefan-guggisberg** [comment]
Underlying issue: https://github.com/adobe/helix-word2md/issues/428

**Comment by stefan-guggisberg** [comment]
underlying issue adobe/helix-word2md#428 has been resolved, closing
