### ISSUE TITLE
default styles broken: hero images too wide

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#157]
https://helix-home-adobe.hlx.page/togetherapart/1-spooky.html

**Comment by rofe** [comment]
workaround in place, waiting for https://github.com/adobe/helix-publish/issues/630 for the final fix.

**Comment by trieloff** [comment]
We should also fix this in helix-pages

**Comment by rofe** [comment]
> We should also fix this in helix-pages

Not sure I'd invest a lot of time in fixing the existing default styling. But we could add the same compatibility script to `head.html` for the time being.

**Comment by rofe** [comment]
See https://github.com/adobe/helix-pages/issues/403

**Comment by rofe** [comment]
Removed workaround
