### ISSUE TITLE
Segmented Lists/Component Tables in Markdown

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#159]
## Overview

In Word and Google Docs, tables are easier to create and manage than lists and are therefore used for scenarios where other constructs in Markdown would look less weird and feel more natural. As outlined in #143, we currenly achieve the correct styling on the client by interpreting the table DOM and transforming it into something more useful.

This discussion proposes a "don't let markdown get weird" approach to these use cases.

### 1. Top-Level Tables become sections, table headings become metadata

The table heading will become metadata, treating the table heading either as a `class` attribute or as straight yaml.

<img width="672" alt="image" src="https://user-images.githubusercontent.com/39613/97148529-92fe2200-176b-11eb-9999-2c0fa492a140.png">

The table above would become:

```markdown

---
class: Special Highlight
---

…

---

```

If there are multiple columns, the headings will be concatenated to consolidate metadata.

### 2. Tables within tables are tables

There is no arbitrary depth nesting of sections, instead a table nested within a table will be represented as a table within a section.

### Rows and columns become segments in a segmented list

Consider the table below:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/39613/97149668-5d5a3880-176d-11eb-831c-d8c5bea5047c.png">

We want to present repeated tuples of `video` and `text`, where each element can be any series of block elements.

The DocBook format has the concept of a [`segmentedlist`](https://tdg.docbook.org/tdg/5.0/segmentedlist.html) which has the notion of titled tuples. Some Markdown extensions have the concept of [Definition Lists](https://www.markdownguide.org/extended-syntax#definition-lists) which has the notion of key-value-pairs:

```markdown
First Term
: This is the definition of the first term.

Second Term
: This is one definition of the second term.
```

This even renders reasonably well in GitHub, which has no support for this syntax extension:

> First Term
> : This is the definition of the first term.
>
> Second Term
> : This is one definition of the second term.

To support block elements, the Markdown blockquote syntax can be borrowed to create something like this:

```markdown

---
class: video text
---

video
: https://www.youtube.com/watch?v=kwLTe-ueHA8
text
: ##### Tues, April 21st
: Tips for Faster Editing with co-host Ryan Connolly
: [https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A8b451283-daa7-4bbe-8bad-55460af8caf8](Download PDF)

video
: https://www.youtube.com/watch?v=818roIRrZm0
text
: ###### Tues, April 28th
: Vlogging Made Easy with co-host Shameless Maya
: [https://documentcloud.adobe.com/link/track?uri=urn%3Aaaid%3Ascds%3AUS%3A9f660f99-2e3e-400e-ae71-6d8410b95b8c](Download PDF)

---
```

The resultant MDAST would look like this:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/39613/97152362-0ce4da00-1771-11eb-831b-0986192a8a7b.png">

If the columns have no title, then `column-<n>` will be used.

The empty line between each table row is mandatory, multiple empty lines are permissible.

The generated HTML should be `div` and `class` based rather than using `dl`, `dt`, and `dd`, so that no CSS reset is needed. Each `seg` in the MDAST should create one `div`

## Proposed Actions

1. get agreement that tables become segmented lists in Markdown and `div`s in HTML
2. upgrade pipeline, word2md, gdocs2md to remark@v9
3. implement a parser for segmented lists
4. implement a to-markdown conversion for segmented lists
5. implement a to-html conversion for segmented lists
6. use it in pipeline
7. and word2md
8. and gdocs2md

**Comment by tripodsan** [comment]
> 1. get agreement

so you want to convert the tables already in word2md and gdocs2md ? instead of doing it client side?

> 2. upgrade pipeline, word2md, gdocs2md to remark@v9

this is unrelated, but already in progress (and it a big mess):
- https://github.com/adobe/helix-pipeline/issues/873
- https://github.com/adobe/helix-word2md/issues/453
- https://github.com/adobe/helix-documents-support/issues/83
- https://github.com/adobe/helix-gdocs2md/issues/360

> 3. implement a parser

I assume for the segmented lists.

> 4. implement a to-text conversion

I assume to-markdown of the segmented lists

> 5. implement a to-html conversion

of the segmented lists...

> 6. use it in pipeline

ok.

> 7. and word2md
> 8. and gdocs2md

so for that we need a general mdast-util-table-to-seglists util.
this is better hosted in helix-document-support.

**Comment by tripodsan** [comment]
On big problem I see is, that the definition list in `mdast` is not a block container, i.e. it doesn't have a `PhrasingContext`:
https://github.com/syntax-tree/mdast#definition

**Comment by trieloff** [comment]
Yes to all questions raised in https://github.com/adobe/helix-home/issues/159#issuecomment-716423076

I'll clarify

**Comment by tripodsan** [comment]
@trieloff I think it would be helpful to have a _POC_ for 4. and 5. so see if we can express what's needed in segmented lists:

a. create some examples in code, using mdast-builder to create the mdast with segmeted lists.
b. create a to-html version
c. create a to-markdown version

**Comment by davidnuescheler** [comment]
this looks great.

i think for the sake of authoring i started using human readable block names like "Special Highlight", but i would expect them to be translated to "special-highlight" as a classname, this way we get something that's intuitive for the author and intuitive css developer.

in a similar way this would be true for the definition list that is turned into `<div>`s with classes, however, i think the transformation from eg. `First Term` to `first-term` should only happen at the time when it becomes related to an html (class) attribute. Maybe that's too confusing as it would yield something like:

```
---
class: first-term second-term
---

First Term
: This is the definition of the first term.

Second Term
: This is one definition of the second term.
```

and

```
<div class="first-term second-term">
    <div>
       <div class="first-term">
        This is the definition of the first term.
       </div>
       <div class="second-term">
        This is one definition of the second term.
       </div>
  </div>
</div>
```

also i think it would be advisable for styling purposes if the class of the outermost div would be `first-term-second-term` rather than `first-term second-term`

**Comment by trieloff** [comment]
> i think for the sake of authoring i started using human readable block names like "Special Highlight", but i would expect them to be translated to `special-highlight` as a classname, this way we get something that's intuitive for the author and intuitive css developer

OK

> also i think it would be advisable for styling purposes if the class of the outermost div would be `first-term-second-term` rather than `first-term second-term`

Isn't `.first-term.second-term` just as easy to select?

**Comment by kptdobe** [comment]
Dumb question: how would you then create... a table ?

**Comment by trieloff** [comment]
> Tables within tables are tables

Put a table inside a table.
