### ISSUE TITLE
New repo: gh-resolve-ref

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-home#164]
Create a new repository with the name `gh-resolve-ref`.  

`gh-resolve-ref` exposes the core functionality of the [helix-resolve-git-ref service](https://github.com/adobe/helix-resolve-git-ref) (i.e. resolving a branch/tag of a github repository to the corresponding commit sha) as a light-weight zero dependency library. 

See https://github.com/adobe/helix-resolve-git-ref/issues/299

## Stuff you can do yourself

- [x] run `npm init @adobe/helix-library` or `npm init @adobe/helix-service`
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [x] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [ ] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference. (*skip for libraries*)
- [ ] Prepare setup of OrgProjectBot
  - [ ] Add a [`.github/org-project-bot.yaml`](https://github.com/adobe/helix-cli/blob/master/.github/org-project-bot.yaml)
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

## Stuff you need an Adobe Org Admin for
- [x] Enable [OrgProjectBot](https://github.com/organizations/adobe/settings/installations/690408)
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)

**Comment by trieloff** [comment]
@stefan-guggisberg do we really need a new repo for this or can we simply republish the existing service as a library, too?

In addition, the missing `helix-` prefix to the repo name will make it likely that the repo will be forgotten during admin tasks in GitHub.

**Comment by stefan-guggisberg** [comment]
> do we really need a new repo for this or can we simply republish the existing service as a library, too?

A separate library is IMO the better option as it allows to avoid unneeded dependencies.

> In addition, the missing helix- prefix to the repo name will make it likely that the repo will be forgotten during admin tasks in GitHub.

I've intentionally omitted the `helix-` prefix since this library is IMO general purpose and not Helix specific (like `git-server`).

**Comment by stefan-guggisberg** [comment]
done: https://github.com/adobe/gh-resolve-ref
