### ISSUE TITLE
repo: helix-pages-version-picker

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#167]
Create a new repository with the name `helix-pages-version-picker`

A preflight service that determines if a repo has opted in to running an upcoming version of helix-pages. To be used with https://github.com/adobe/helix-publish/pull/627

## Stuff you can do yourself

- [x] run `npm init @adobe/helix-library` or `npm init @adobe/helix-service`
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [x] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [ ] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference. (*skip for libraries*)
- [x] Prepare setup of OrgProjectBot
  - [x] Add a [`.github/org-project-bot.yaml`](https://github.com/adobe/helix-cli/blob/master/.github/org-project-bot.yaml)
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

## Stuff you need an Adobe Org Admin for
- [x] Enable [OrgProjectBot](https://github.com/organizations/adobe/settings/installations/690408)
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)

**Comment by trieloff** [comment]
#### In an ideal world, picking a version would work like this:

1. user creates a branch `breaking202011` – all content served from that branch will pick the `202011` version automatically
2. user merges the branch `breaking202011` into `main` – now `main` picks the `202011` version too*

**Note:** version picking is an expression of preference, helix-pages can decide not to honor that preference, for instance because the picked version is too old or too new. This is not the subject of this discussion.

#### In the real world:

1. can be implemented easily and quickly. If the branch name matches the pattern, we know the preference
2. is hard to do quickly. We can use the [compare two commits](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#compare-two-commits) API to check if `breaking202011` has commits that `main` does not have (in which case we'd assume it has not been merged) but that API access is rate limited (60 requests per hour per IP in the normal case, up to 12,500 requests per hour if users have installed the Helix GitHub app)

#### An alternative:

1. as before
2. any branch that has a `helix-version.txt` (filename TBD) file in the root directory will express whatever version number is the content of that file.

We can fetch that file relatively quickly and without rate limits from raw, and it would carry over when the branch is being merged.

#### Stuff to consider

- [ ] could we cache the merge status? Yes, but we can't invalidate the cache without a bot, so merges would not work immediately, and possibly break things
- [ ] could we create the `helix-version.txt` file automatically upon branch creation? Yes, but we'd need the GitHub app for that.

**Comment by tripodsan** [comment]
I think to avoid too much confusion, a possible `helix-version.txt` should only be effective in the `main` branch. it's potentially confusing to have a `helix-version.txt` with the value of `breaking-november` in a branch called `breaking-december`.

**Comment by trieloff** [comment]
If `helix-version.txt` is only considered in the `main` branch, then you cannot have multiple branches that target the same breaking release and the semantics will of the `helix-version.txt` will change upon merge. With your example, the `breaking-november` branch will work perfectly as long as it is a separate branch, but break as soon as merged into `main`.

If `helix-version.txt` is always considered, your `breaking-november` branch may be broken, because you do not yet adopt the breaking December changes, but there won't be a surprise when merging it.

**Comment by tripodsan** [comment]
btw: the automatic detection based on the commit history doesn't always work if:
- they do a squash- or rebase-merge
- there is nothing to merge...

An alternative would be to store the version-per-project in a _database_.

**Comment by tripodsan** [comment]
created here: https://github.com/adobe-rnd/helix-version-picker

@trieloff can you move to `adobe` ?

**Comment by trieloff** [comment]
@tripodsan if you make me an admin in the project…

**Comment by tripodsan** [comment]
> @tripodsan if you make me an admin in the project…

try again....

**Comment by trieloff** [comment]
<img width="2556" alt="Screen Shot 2020-12-07 at 10 10 21" src="https://user-images.githubusercontent.com/39613/101331613-872a7300-3874-11eb-9a36-866dcdddafb6.png">

Still don't have the settings button
