### ISSUE TITLE
remove algolia specifics from sources

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#172]
## Overview
since helix doesn't use algolia anymore, it's specifics should be removed from the sources.

## Details
remove algolia specifics from:

- [x] https://github.com/adobe/helix-index-files
- [x] https://github.com/adobe/helix-simulator
- [ ] https://github.com/adobe/helix-publish
- [x] https://github.com/adobe/helix-shared
- [x] https://github.com/adobe/helix-cli
- [x] https://github.com/adobe/helix-pages

**Comment by tripodsan** [comment]
@davidnuescheler, @trieloff what is your opinion?

**Comment by trieloff** [comment]
I see no rush and would wait a bit until we know for sure that we won't make use of it.

**Comment by tripodsan** [comment]
closing since helix-published will be retired soon.
