### ISSUE TITLE
Clarify Getting Started with Helix

### ISSUE THREAD

**Issue by acollign** [adobe/helix-home#18]
A couple of things that deserves clarifications, a.k.a. state what may sound obvious:
- nvm can be used to install and setup a supported version of node 
- apihost must be adobeioruntime.net instead of runtime.adobe.io
- HLX_FASTLY_NAMESPACE is the Service ID
- HLX_FASTLY_AUTH is a personal token that one needs to create

**Comment by rofe** [comment]
@acollign thanks! Care to create a PR? :)

Note that documenting all HLX_* variables is already tracked under https://github.com/adobe/helix-cli/issues/698
