### ISSUE TITLE
Rootless Setup

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#183]
## Overview

Our current routing assumes that the helix site is mounted at the domain root, which means we have special absolute paths. To enable rootless setup, we convert the most important absolute magic paths into magic relative paths.

Key requirements have beet outlined here https://github.com/adobe/helix-publish/pull/718#issuecomment-772697351

## Details
- [x] `helix-publish` should serve blobs using the `_media_{hash}.{extension}` path https://github.com/adobe/helix-publish/pull/724
- [x] `helix-static` should serve icons using the `_icons_{name}.svg` or `_icons_.svg#{name}` path https://github.com/adobe/helix-static/pull/491
- [ ] `helix-pipeline` should create links using the above relative paths

**Comment by davidnuescheler** [comment]
as mentioned in https://github.com/adobe/helix-publish/pull/718#issuecomment-772697351 i think we should deprecate
CGI-BIN,  Queries, Fonts  and /icons/ and leave them in their current state and not support those for a rootless setup.

the changes that are in breaking march, are forcing existing project to change to an undesirable state for now reason.

**Comment by trieloff** [comment]
I just reverted the icon changes in the pipeline.
