### ISSUE TITLE
consistent default branch handling for surfing and purging

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#187]
**Confusing Default Branch handling**

- visitor surfs usually w/o branch
   https://spark-website--adobe.hlx.page/marketing/frictionless-resize.md
- fastly (vcl) uses `master` as default `ref` if missing
- github serves resources on master branch, even if there is only a main branch, eg: https://raw.githubusercontent.com/adobe/spark-website/master/fstab.yaml
- pipeline fetches content with `{ref}--{repo}--{owner}`, so even if the project has `main` as default branch, `master` is used for content eg:
  https://master--spark-website--adobe.hlx.page/marketing/frictionless-resize.md instead of
  https://main--spark-website--adobe.hlx.page/marketing/frictionless-resize.md
- helix-purge uses ref from sidekick or defaults to master, so in the above example, the wrong `md` would be purged
- even preflight requests need to read from default branch, so it would be expensive to use git-resolve-ref to detect the default branch.
- `.json` resources are usually fetched relative to the base url, so if a surfer would use `https://main--...` it would use the _wrong_ cache.

**Solution**

1. add edge dictionary for all projects that don't use `main` as default branch
2. VCL consults edge dictionary if branch specifier is missing and sets the `ref` header/param
3. in order to avoid surfers to use the branch specifier if not needed (eg `main--`), fastly sends redirect.
4. pipeline uses same addressing as the surfer would, i.e. fetches the `md` w/o branch specfier.
5. helix-purge purges the resources and html always w/o branch specifier (if `main` or `master`)

**Comment by rofe** [comment]
As a workaround, we could also take advantage of github's automagic handling of an inexistent `master` branches, and in `helix-purge` always purge both `master` and `main` `md`s if the specified branch/ref is one or the other.

**Comment by kptdobe** [comment]
I would get rid of any support for `master` as default and treat 'master` as a normal branch non default branch. This would only require to patch the config our existing customers still on `master`.
Might be a good breaking-april task ;)

**Comment by trieloff** [comment]
The edge dictionary approach won't scale beyond 10k entries and will be hard to manage.

I agree with @kptdobe that a hard break would be the cleanest solution.

**Comment by tripodsan** [comment]
> The edge dictionary approach won't scale beyond 10k entries and will be hard to manage.

as I said, only the projects that are not on main. so as an exception. we can have a non-secret dict that can be easily edited online.

> I agree with @kptdobe that a hard break would be the cleanest solution.
ok.

still I think that fastly should enforce the default branch. so even if we don't use the edge dict, points 2-5 still apply.

**Comment by davidnuescheler** [comment]
i think the benefits of omitting the branch in the URL is limited, so maybe we should just redirected to the fully qualified `main--` or `master--` if someone doesn't specify a branch in the hostname

**Comment by trieloff** [comment]
That would be a clear way to handle it. We just need to update the outer CDNs.

**Comment by tripodsan** [comment]
so to recap the steps, then:

- in order to have consistent surfing, fastly sends redirect to `main--*` if branch specifier is missing or `master--`.
- pipeline uses same addressing as the surfer would, i.e. fetches the md with branch specfier: `main--`
- helix-purge purges the resources and html always with branch specifier (if main or master)

**Comment by trieloff** [comment]
If you specify `master--` in the domain, there is no need to redirect. We just should not assume it to be the default.

**Comment by tripodsan** [comment]
> If you specify `master--` in the domain, there is no need to redirect. We just should not assume it to be the default.

we won't support `master` anymore...and in order to avoid confusion (because it would still work, because github has the fallback. eg https://raw.githubusercontent.com/adobe/spark-website/master/fstab.yaml). and we don't want the surfer to use a url that we don't flush anymore. so better redirect it to `main--`

**Comment by trieloff** [comment]
Why shouldn't we support `master--` anymore? GitHub might have an alias `master->main` for repos that renamed their default branch, but there is no alias from `main` to `master` (e.g. https://raw.githubusercontent.com/trieloff/helix-demo/main/foo.md vs https://raw.githubusercontent.com/trieloff/helix-demo/master/foo.md)

With an enforced redirect, we break all repositories that have a `master` branch and do not want to switch to a `main` branch.

I think this is a very strange thing for us to enforce in a very heavy-handed way. I'm all for changing the default, but I don't see that it is our job to create a blocklist of words that are not allowed in branch names.

**Comment by tripodsan** [comment]
as I said...to avoid confusion.... I think it's better to enforce `main`.  
we can tend to all the repositories that still use `master` and rename their branched manually.

**Comment by trieloff** [comment]
I don't think that's worth it.

**Comment by rofe** [comment]
Do we want to _forbid_ `master` as default repo? While I definitely think we should encourage and propagate the use of `main`, but not necessarily force a naming convention on customers.

**Comment by tripodsan** [comment]
> Do we want to _forbid_ `master` as default repo? While I definitely think we should encourage and propagate the use of `main`, but not necessarily force a naming convention on customers.

not forbid, but not support to be default. if `ref` is missing, always redirect to `main`.
and only purge `main`.

we can allow, that users still surf `master--` if they really want. but they won't have purging.

**Comment by trieloff** [comment]
@tripodsan (emphasis mine)

> in order to have consistent surfing, fastly sends redirect to `main--*` if branch specifier is missing or **`master--`**

The forced redirect from `master--` to `main--` is what I have been objecting. The redirect from missing branch to `main--` is fine. The `master--` redirect is akin to *forbidding* `master` as a branch name.

The proposal in https://github.com/adobe/helix-home/issues/187#issuecomment-804497720 I do agree with:

- missing branches get redirected to `main--`
- pipeline uses same addressing as the surfer would, i.e. fetches the md with branch specfier: `main--`
- helix-purge purges the resources and html always with branch specifier (if `main` or `master`)

If you send a purge to a missing ref, do not expect `master--` to magically get purged. If you send a HLXPURGE request to `master--`, it will get purged, of course.

**Comment by rofe** [comment]
> we can allow, that users still surf `master--` if they really want. but they won't have purging.

Yes they would, as long as the `host` param includes `master--*`, right?

**Comment by trieloff** [comment]
See also https://github.com/adobe/spark-website/pull/121 – it looks like the spark site has some trouble with `main--` somewhere.

**Comment by rofe** [comment]
Handled in https://github.com/adobe/helix-pages/pull/867.

**Comment by tripodsan** [comment]
this can be closed as we have now strict(er) rules for default branch handling in helix3.
