### ISSUE TITLE
Helix Pages Themes as Git Repositories

### ISSUE THREAD

**Issue by bdelacretaz** [adobe/helix-home#19]
The demo by @kptdobe this morning prompted this idea: at some point we'll need themes for Helix Pages. 

I quite like how they are handled in GitHub pages: each theme is provided by a GitHub repository, like https://github.com/pages-themes/hacker . A config file in your content repository selects which theme to use, and if you want to override part of the theme you just copy the corresponding file(s) in your content repository and modify it.

The problem might be backwards compatibility, when a theme is updated your changes might break. Pointing to a specific version/tag of the them would help with that.

(I suppose creating this ticket here is correct as it's a general product design discussion)

**Comment by rofe** [comment]
I like this idea. This could be achieved by treating the theme repo as the static repo behind the scenes (I’m thinking Helix Pages VCL only because we likely don’t want to impose a helix-config.yaml at this stage yet)
