### ISSUE TITLE
Create new private repository for helix3 admin

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#198]
Create a new **private** repository with the name `helix-admin`

it will be a minimal service that handles publish (and preview) operations for helix 3.

## Stuff you can do yourself

- [x] run `npm init @adobe/helix-library` or `npm init @adobe/helix-service`
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [ ] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [ ] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference. (*skip for libraries*)
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

## Stuff you need an Adobe Org Admin for
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)
- [ ] Share the [`ADOBE_BOT_NPM_TOKEN` org secret](https://github.com/organizations/adobe/settings/secrets/actions/ADOBE_BOT_NPM_TOKEN)

**Comment by tripodsan** [comment]
@trieloff @stefan-guggisberg can you help? thanks

**Comment by stefan-guggisberg** [comment]
done

**Comment by tripodsan** [comment]
senks!
