### ISSUE TITLE
Migrate getting started doc to project-helix.io

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#2]
Like the [60 seconds guide](https://github.com/adobe/project-helix.io/blob/master/index.md), I think the more detailed [getting started doc](https://github.com/adobe/helix-home/blob/master/getting-started.md) should be moved to `project-helix.io` and published on https://www.project-helix.io.

**Comment by rofe** [comment]
We should tackle this in conjunction with https://github.com/adobe/helix-cli/issues/711

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
