### ISSUE TITLE
Create: helix-media-bus-migration

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#210]
Create a new repository with the name `helix-media-bus-migration`
it will contain the function to migrate from the azure to the s3 media bus.

## Stuff you can do yourself

- [x] run `npm init @adobe/helix-library` or `npm init @adobe/helix-service`
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [ ] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [ ] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference. (*skip for libraries*)
- [ ] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)

## Stuff you need an Adobe Org Admin for
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)
- [ ] Share the [`ADOBE_BOT_NPM_TOKEN` org secret](https://github.com/organizations/adobe/settings/secrets/actions/ADOBE_BOT_NPM_TOKEN)

**Comment by stefan-guggisberg** [comment]
done: https://github.com/adobe/helix-media-bus-migration
