### ISSUE TITLE
create new public repository `helix-html2md`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#258]
Create a new service repository with the name `helix-html2md`.

it will contain the code for a service that reads content from a `Helix Generic HTML Content` source and transforms it to markdown (similar to word2md and gdocs2md). The repository will also serve as a start point to define the helix generic content model.

## Stuff you can do yourself

- [x] run `npm init @adobe/helix-library` or `npm init @adobe/helix-service`
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [ ] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)

### for services
- [x] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference.
- [x] Add a `CIRCLECI_TOKEN` to the repository secrets.

## Stuff you need an Adobe Org Admin for
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)

### for libraries
- [ ] Share the [`ADOBE_BOT_NPM_TOKEN` org secret](https://github.com/organizations/adobe/settings/secrets/actions/ADOBE_BOT_NPM_TOKEN)

**Comment by kptdobe** [comment]
https://github.com/adobe/helix-html2md
