### ISSUE TITLE
Theme: Documentation and Examples

### ISSUE THREAD

**Issue by bdelacretaz** [adobe/helix-home#31]
This is a "thematic ticket" meant to collect general discussions about documentation and examples along with links to more specific tickets.

The idea is that "if it's about documentation it should be discussed or referenced here". We'll see how that works as we progress!

**Comment by bdelacretaz** [comment]
We've been discussing whether repository templates apply to Helix examples. For now  I suggest that we evolve example repositories organically, and maybe create a template later if a pattern emerges.

**Comment by bdelacretaz** [comment]
Here's a list of links related to docs and examples, feel free to expand:
* https://github.com/adobe/helix-cli/issues/933 - repurpose hlx demo
* https://github.com/adobe/helix-cli/issues/711 - improve developer experience
* https://github.com/adobe/helix-cli/issues/698 - document HLX_ env variables
* https://github.com/adobe/helix-cli/issues/491 - improve full example
* https://github.com/adobe/helix-cli/issues/828 - how to setup Helix bot
* https://github.com/adobe/helix-pages/issues/14 - example project repos
* https://github.com/adobe/helix-pages/issues/3 - make demo project look great
* https://github.com/adobe/project-helix/issues/398 - helix docs use cases (private but should move)
* https://github.com/adobe/helix-home/issues/27 - Example Zero
* https://github.com/adobe/helix-home/issues/29 - review developers experience at step 3
* https://github.com/adobe/helix-home/issues/25 - getting started 2.0
* https://github.com/adobe/helix-home/issues/18 - clarify getting started
* https://github.com/adobe/helix-home/issues/14 - document Helix cookies

**Comment by bdelacretaz** [comment]
I assigned this ticket to myself with the aim or coordinating these efforts. Everybody's welcome to contribute to this of course.

**Comment by bdelacretaz** [comment]
## Three main personas for documentation?
The discussion at https://github.com/adobe/helix-home/pull/26 shows that how we document things can be _very_ different depending on who we're talking to.

For people who are familiar with GitHub and Markdown (typically those who have already used GitHub Pages), an example repository like https://github.com/bdelacretaz/helix-example-zero can be sufficient, with the README explaining the basics and pointers to reference documentation as required.

I think people who in addition to that are familiar with Node.js would be happy with another example repository that uses Helix's programmable features such as custom rendering templates, https://github.com/adobe/helix-pipeline functionality, access to external services etc. Again, with pointers to reference docs, but starting from readable example code.

The rest is people who are not familiar with GitHub, Markdown or Node.js style programming. We might need more descriptive step-by-step documentation for those, but imposing such step-by-step docs on the others risks wasting their time.

In summary, at this point I suggest considering 3 main personas:
1. People who have **knowledge of GitHub and Markdown** and ideally have used something like GitHub Pages before
2. People who in addition to that are **familiar with Node.js style programming**
3. People who have **none of the above knowledge** and need step-by-step instructions, along with pointers to books and tutorials where they can acquire the required knowledge.

As Helix evolves I think it's more efficient to focus on the first two personas first, for which we can write examples with automated tests (like https://github.com/bdelacretaz/helix-example-zero) to make sure the examples don't go stale.

Step-by-step "prose" documentation is more likely to get out of sync so I'd rather tackle that later once we're confident that the modules that we are documenting are stable in terms of API and usage.

**Comment by bdelacretaz** [comment]
## Memorable names for our three main personas

Based on recent discussions and commits it looks like the above personas match our needs at this point. I think we need easy to remember names for them, how about:

* **Mark Downlix** for someone who has knowledge of GitHub and Markdown and ideally has used something like GitHub Pages before
* **Janis Nodelix** for someone who in addition to that is familiar with Node.js programming
* **Betty Gayner** for someone who needs step-by-step instructions

**Comment by bdelacretaz** [comment]
## Names and content of the main Helix examples
I've thought a bit more about the examples naming, how about this (using the tentative persona names  listed above):

1. The `helix-pages-example` repository is where Mark can start. It uses only content files: Markdown, CSS, static HTML, images etc.
1. The `helix-full-example` repository is where Janis can start. In addition the content files, it demonstrates Helix features that require programming: the pipeline, custom HTL templates, etc.
1. Betty is expected to start with the #26 Getting Started guide

The example repos _might_ use branches for progressive disclosure but I think we should start by fully fleshing them out and later have a look at how to deliver them in smaller units, if needed.

**Comment by rofe** [comment]
I don't think the separation between `pages` and `full` in the names will be intuitive. It implies that you are exiting the _Helix Pages_ realm after playing with the first example repository (steps 1 - 4 in #26), and entering the fully custom realm where you handle deployment and publication yourself. But that's not entirely true: as an intermediate step, we want _Helix Pages_ to be able to deal with your custom code (step 5) without requiring you to sign up for a Runtime or Fastly account just yet. That would likely be dealt with in step 7 and onwards.

**Comment by bdelacretaz** [comment]
> I don't think the separation between pages and full in the names will be intuitive... 

Ok, understood, we don't want to create an artificial separation between Pages and non-Pages.

I don't like "advanced" in general as it's quite vague...

How about "basic" and "full" samples for now? Or "Mark" and "Janis", naming them after the personas...

We might need a chat session to discuss these names, async discussions on names is quite hard.

**Comment by bdelacretaz** [comment]
We did chat with @rofe and agreed to name the example repositories `helix-example-basic`and `helix-example-advanced`. I'll create those and copy the contents of https://github.com/bdelacretaz/helix-example-zero to example-basic as a starting point.

**Comment by bdelacretaz** [comment]
Both https://github.com/adobe/helix-example-basic and https://github.com/adobe/helix-example-advanced are now in a state where we can add more meaningful examples to them - and adapt their tests accordingly.

Both repositories have a few "local" issues and a number of TODO in various places.

**Comment by bdelacretaz** [comment]
> I don't think the separation between pages and full in the names will be intuitive. 

This came up again at the Strasbourg Hackathon - the consensus IIUC is that moving from basic Helix Pages to more complex setups should be a continuum, without really having to "switch modes".

Having to enable a GitHub bot/app to access advanced features is fine, but having to switch to command-line tools is a mode switch that we should be able to avoid.

**Comment by rofe** [comment]
This will need to be rethought for Helix 3. Won't fix for Helix 2.
