### ISSUE TITLE
Create a new repository with the name helix-example-basic

### ISSUE THREAD

**Issue by bdelacretaz** [adobe/helix-home#34]
Create a new repository with the name `helix-example-basic`

- [x] Use [`helix-library`](https://github.com/adobe/helix-library) or [`helix-service`](https://github.com/adobe/helix-service) template
- [x] Add tags to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [ ] Upload a social media image
- [x] Set the repository description
- [x] Update the repository `README.md` (search for `adobe/helix-service` or `adobe/helix-library`)
- [ ] Set up Project Bot
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
- [ ] Set up Greenkeeper 
> *Note:* Greenkeeper will find your new repository automatically, but it might file an issue that it cannot get the build status if you haven't set up CircleCI yet. In this case, go to [Greenkeeper](https://account.greenkeeper.io/account/adobe) and click the "fix repo" button
- [ ] Set up [LGTM](https://github.com/organizations/adobe/settings/installations/870657)
- [ ] Set up [Commitlint](https://github.com/organizations/adobe/settings/installations/728398)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`
- [x] Set up [Snyk](https://app.snyk.io/org/adobe-org/sources/9a3e5d90-b782-468a-a042-9a2073736f0b/add)

**Comment by bdelacretaz** [comment]
Repo created at https://github.com/adobe/helix-example-basic/

**Comment by tripodsan** [comment]
I don't think that our helix-pages example repos should be based on our helix-* templates.
they should be minimal and not contain too much boilerplate.

**Comment by bdelacretaz** [comment]
I started with that template as a basis but trimmed down after that - I think https://github.com/adobe/helix-example-basic is minimal now, or do you see things that shouldn't be there?

The test code is "hidden" in the https://github.com/adobe/helix-example-basic/tree/test-code branch, that one can probably be trimmed down a bit more. But it's meant for developers of the example, not really for its users.

**Comment by rofe** [comment]
Great start. I don't think we need:
- htdocs - if I understood @davidnuescheler correclty, that's for code repos only. Content repos should be able to overlay "statics" just by putting files in the repo's root.
- .gitignore - this only contains files and folders relevant for "coding", so I don't think it's needed in a content repo.

**Comment by tripodsan** [comment]
closing. in helix 3 there is only: https://github.com/adobe/helix-pages-starter
