### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#347]
For security and audit purposes, we should keep a trail of every write operation on `admin.hlx.page`:

From [Wikipedia](https://en.wikipedia.org/wiki/Audit_trail):
> An audit trail (also called audit log) is a security-relevant chronological record, set of records, and/or destination and source of records that provide documentary evidence of the sequence of activities that have affected at any time a specific operation, procedure, event, or device. Audit records typically result from activities such as financial transactions, scientific research and health care data transactions, or communications by individual people, systems, accounts, or other entities.

**Information:**
- Timestamp
- User ID/email
- Action
- URL
- ...

**Persistence & Access:**
Persistence should be indefinite (or a very, very long time) and admin users at customer should have access to it.

**Comment by rofe** [comment]
@dominique-pfister reviewed the current state with @tripodsan: can we change the columns to split up `url` into `route`, `owner`, `repo`, `ref`, `path`, `search` (consolidating the existing`path` column). This will allow admins to show/hide columns.

cc @davidnuescheler

**Comment by tripodsan** [comment]
see https://github.com/adobe/helix-admin/issues/520, (`method` also got forgotten):

```
timestamp, duration, user, status, method, route, owner, repo, ref, path, search
```

**Comment by dominique-pfister** [comment]
Implemented as described, including the column list. Can it be closed?

**Comment by rofe** [comment]
Based on latest conversations, we'll need a way to read the log via admin API, `GET /log`, but also have the ability to log custom events via `POST /log` with a JSON payload. The log itself should not be stored in Excel, but directly in S3.

cc @tripodsan @dominique-pfister

**Comment by rofe** [comment]
Documenattion: https://www.hlx.live/docs/admin.html#tag/log

**Comment by 3vil3mpir3** [comment]
@rofe Is there documentation on what is returned in these logs?

**Comment by rofe** [comment]
@dominique-pfister is working on a documentation. We should probably add a link here when it's published.

**Comment by 3vil3mpir3** [comment]
Thanks @rofe, +1 to adding the doc link here.  

The ask from Pfizer: would/could this logging contain user data relational to preview/publish (e.g. I published something, it has the datestamp of when I did that, AND that it was me who did it).  If that's the case, we'll await the documentation and I'll mark their internal Jira as closed/done. If not, we'd probably need an enhancement ticket for that specific ask.  I have to imagine other customers (especially those in regulated industry) would also need that type of data available via API.

**Comment by dominique-pfister** [comment]
> The ask from Pfizer: would/could this logging contain user data relational to preview/publish (e.g. I published something, it has the datestamp of when I did that, AND that it was me who did it

Yes, it contains all that information.

**Comment by 3vil3mpir3** [comment]
Thanks @dominique-pfister!
