### ISSUE TITLE
Create new repository helix-s3-change-listener

### ISSUE THREAD

**Issue by dominique-pfister** [adobe/helix-home#389]
Create a new service repository with the name `helix-s3-change-listener`

## Stuff you can do yourself

- [x] run `npm init @adobe/franklin-library` or `npm init @adobe/franklin-service`
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [ ] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [x] List your repository in [AWS IAM](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/roles/details/helix-gh-deploy-config-service?section=trust_relationships)

## Stuff you need an Adobe Org Admin for
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)

### for libraries
- [ ] Share the [`ADOBE_BOT_NPM_TOKEN` org secret](https://github.com/organizations/adobe/settings/secrets/actions/ADOBE_BOT_NPM_TOKEN)

**Comment by kptdobe** [comment]
Created https://github.com/adobe/helix-s3-change-listener
