### ISSUE TITLE
Document the differences and switch between Helix Pages and non-Pages

### ISSUE THREAD

**Issue by bdelacretaz** [adobe/helix-home#39]
## Intended Audience
Helix users

## Related Issues

- https://github.com/adobe/helix-bot/issues/109

We need to explain the differences between Helix Pages and non-Pages and what causes the switch from one to the other mode.

And maybe also find a more descriptive name for the non-Pages mode unless we have one already.

As per https://github.com/adobe/helix-bot/issues/109 a GitHub repository is considered to be a Helix Pages repo unless:

- it has a `.github/helix-bot-config.yaml(.gpg)`
- it has a `src` directory
- it has a `helix-config.yaml`

And BTW these rules should probably be part of some shared code to be reusable and strictly defined.

Linking this to https://github.com/adobe/helix-home/issues/31, the "doc" theme ticket.

**Comment by rofe** [comment]
>  a more descriptive name for the non-Pages mode

I guess it's "just" _Helix_ then :)

As for the criteria for _Helix Pages_ eligibility:
> it has a .github/helix-bot-config.yaml(.gpg)

I don't think this is related with _Helix Pages_ in any way. The project bot is used to make issues created in one of the official Helix repos appear on the [Helix Board](https://github.com/orgs/adobe/projects/2)
> it has a src directory

I don't think that the presence of a `src` folder alone should already eject you from _Pages_ land... it might be desirable to give customers a certain level of control over the rendering while still having everything auto deployed and published by _Helix Pages_...
> it has a helix-config.yaml

That's probably where the customer is starting to get into "enterprise mode" and must start deploying and publishing their own site.

See also [getting-started-2.0.md](https://github.com/adobe/helix-home/blob/master/getting-started-2.0.md) which is an attempt to describe a desired future dev experience.

**Comment by tripodsan** [comment]
closing won't fix as it doesn't apply to helix 3 anymore.
