### ISSUE TITLE
Copyright year is 2023 in Helix website

### ISSUE THREAD

**Issue by Adobe-G11N-I18N-L10N-Team** [adobe/helix-home#390]
**Description**
Copyright year is 2023 in Helix website

**To Reproduce**
1. Go to https://www.aem.live/home
2. Scroll to the bottom of page

**Expected behavior**
Copyright year is 2024

**Screenshots**
![copyright year](https://github.com/adobe/helix-sidekick-extension/assets/144205585/209e3704-8c03-477e-95ac-287670341ae8)

**Comment by rofe** [comment]
Fixed
