### ISSUE TITLE
create new private repository: helix-config-storage

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#412]
Create a new service|library repository with the name `helix-config-storage`

## Stuff you can do yourself

- [ ] run `npm init @adobe/franklin-library` or `npm init @adobe/franklin-service`
- [ ] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [ ] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [ ] Set the repository description
- [ ] List your repository in [AWS IAM](https://us-east-1.console.aws.amazon.com/iam/home?region=us-east-1#/roles/details/helix-gh-deploy-config-service?section=trust_relationships)

## Stuff you need an Adobe Org Admin for
- [x] Enable [Renovatebot](https://github.com/organizations/adobe/settings/installations/1325372)

### for libraries
- [ ] Share the [`ADOBE_BOT_NPM_TOKEN` org secret](https://github.com/organizations/adobe/settings/secrets/actions/ADOBE_BOT_NPM_TOKEN)

**Comment by kptdobe** [comment]
Created https://github.com/adobe/helix-config-storage

**Comment by kptdobe** [comment]
Almost done. For some reason, I cannot add the [ADOBE_BOT_NPM_TOKEN org secret](https://github.com/organizations/adobe/settings/secrets/actions/ADOBE_BOT_NPM_TOKEN) token - repo is not in the list. I assume it needs a little bit time to update the repo list. Will try later. If I forget, just ping me.

**Comment by tripodsan** [comment]
> Will try later. If I forget, just ping me.

afaik this isn't available for private repos

**Comment by kptdobe** [comment]
Correct. Some private repos are in the list but when I check on the repo, the secret is not availabe.
