### ISSUE TITLE
Getting Started 2.0: document how to configure proxy strains

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#43]
We need to replace the dummy section on proxying legacy sites in [getting-started-2.0.md](https://github.com/adobe/helix-home/blob/master/getting-started-2.0.md) with actual documentation. Source: https://github.com/adobe/helix-shared/blob/master/docs/proxystrain.schema.md

This is a follow up task from #25.

**Comment by tripodsan** [comment]
closing won't fix as it doesn't apply to helix 3 anymore.
