### ISSUE TITLE
Getting Started 2.0: explain how to separate code and content

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#44]
We need to replace the dummy section on separate code and content repos in [getting-started-2.0.md](https://github.com/adobe/helix-home/blob/master/getting-started-2.0.md) with actual documentation. Source: https://github.com/adobe/helix-home/blob/master/getting-started.md#set-up-github-repositories

This is a follow up task from #25.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
