### ISSUE TITLE
Introduce chaos engineering to increase resilience

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#45]
One of the DevOps principles is to harden the production environment by causing disruptions intentionally, so failures can be found and fixed before they happen in an uncontrolled manner.

See also:
- https://en.wikipedia.org/wiki/Chaos_engineering
- [Netflix' Chaos Monkey](https://github.com/netflix/chaosmonkey)
- [Google's DiRT](https://queue.acm.org/detail.cfm?id=2371516)

**Comment by tripodsan** [comment]
- Step 1: create a high load on Adobe I/O Runtime.
- Step 2: observe the chaos.

**Comment by koraa** [comment]
Doin't you think doing that sort of testing is a bit premature? Especially since we don't really have control over our infrastructure?

**Comment by trieloff** [comment]
One way to build this would be follow the approach taken by epsagon (see https://github.com/epsagon/epsagon-node/blob/master/src/events/http.js) and use https://www.npmjs.com/package/shimmer to patch the `http` module in nodejs to add random delays and errors

**Comment by koraa** [comment]
@trieloff Do we have any systems in place to mitigate random delays and errors right now?

**Comment by trieloff** [comment]
> Do we have any systems in place to mitigate random delays and errors right now?

You mean other than the NUI team? 😉 No.

**Comment by koraa** [comment]
NUI?

**Comment by trieloff** [comment]
NUI is asset processing on Adobe I/O Runtime.

**Comment by koraa** [comment]
@trieloff I see, thanks for the information!

So how would NUI react to mitigate delays? What actions would it take to handle the random errors?

**Comment by rofe** [comment]
@koraa I believe @trieloff's (half) joke was referring to the I/O Runtime load tests performed by NUI a while back, which were causing several service outages on our end. Mitigations against such behavior should ideally be put in place by the I/O Runtime team.

**Comment by kptdobe** [comment]
Closed during backlog grooming session during hackathon. Reopen if needed or open a new one.
