### ISSUE TITLE
Use renovatebot over greenkeeper to update deps in bulk once a week

### ISSUE THREAD

**Issue by koraa** [adobe/helix-home#47]
Renovatebot can be configured to open one PR per repo every week with *all* available updates:

https://renovatebot.com/docs/configuration-options/#schedule

     schedule: "at 7:00 am on Monday"
     timezone: "Europe/Zurich"

**Comment by rofe** [comment]
Agreed for regular dependency updates. But can PRs for high urgency updates (e.g. security fixes) be excluded from the weekly cadence and opened right away?

**Comment by trieloff** [comment]
I'd suggest we try renovatebot on a single repository before we decide to make the switch.

**Comment by rofe** [comment]
As far as I can tell, there are no major hiccups with renovatebot so far. Should we go ahead and replace greenkeeper in all helix-* projects?

**Comment by trieloff** [comment]
-1

I don't like the monolithic PRs that renovatebot is creating, which more often than not break, making it hard to isolate the issue:

https://github.com/adobe/helix-cli/pull/1110
https://github.com/adobe/helix-cli/pull/1105
https://github.com/adobe/helix-cli/pull/1124

For our own dependencies it's also annoying that we have to wait a week for changes to propagate, adding another manual element into our release process.

If the goal is to reduce the volume of Greenkeeper PRs, we can simply move to `^`-versioned dependencies for anything outside Project Helix, while keeping version-pinned dependencies.

**Comment by kptdobe** [comment]
Not yet pro or con, but renovate knows about CircleOrbs: https://github.com/adobe/helix-cli/pull/1132
which is awesome for me maintaining the only orb we have... :)

**Comment by trieloff** [comment]
Our Greenkeeper subscription renews in October, so we can make a decision beforehand.
