### ISSUE TITLE
Experimental fetch from google docs

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#52]
Using @davidnuescheler's experimental googledocs->markdown generator `[0]`, it should be possible to fetch the markdown directly in the pipeline.

The ID of the document is either passed through the resource path:
- https://helix-test-davidnuescheler.project-helix.page/googledocs/sdfasdfasdfasf1241234.html
- or via google docs path: https://helix-test-davidnuescheler.project-helix.page/googledocs//Helix+Hackathon+Part+V.html
- or inserted as embed in a parent document. eg: `[googledocs](sdfasdfasdfasf1241234)`

`[0]`: https://helix-test-davidnuescheler.project-helix.page/googledocs.html

**Comment by trieloff** [comment]
I think the best place for this is helix-embed. Just detect google docs URLs, then turn them into embeddable HTML and you are done.

**Comment by tripodsan** [comment]
no, the idea is to turn the google doc into markdown, and either use it as complete resource (i.e. fetch it in the fetch step), or as part of the mdast.

**Comment by trieloff** [comment]
Then we need to come up with a good way of picking the right backend for the `fetch` method in the pipeline.

**Comment by tripodsan** [comment]
> Then we need to come up with a good way of picking the right backend for the `fetch` method in the pipeline.

this is only a demo for now... I would just install a pre-fetch and tweak the action params accordingly.

**Comment by kptdobe** [comment]
@tripodsan Are you still making progress here or is it done ?

**Comment by tripodsan** [comment]
closing for now.
