### ISSUE TITLE
add possibility to deploy multiple code repos to same 2nd level domain.

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-home#53]
**Is your feature request related to a problem? Please describe.**
- As owner of a 2nd level domain, eg: mybusiness.com, I want to be able to run several projects. eg: `www.mybusiness.com`, `info.mybusiness.com`. 
- as a helix developer I want to reuse my existing domain for several projects, because I don't want to setup multiple domains. eg: `dev.mysite.com`, `project4.mysite.com`, `test.mysite.com`, `tripod-test.mysite.com`

**Describe the solution you'd like**
Ideally, I want to be able to specify the domain in the `helix-config.yaml` and use the same fastly service. each _project_ would deploy to an own action-package.

**Describe alternatives you've considered**
the only possibility is to create multiple branches in the same repository and they use deploy flags, like `--only` to deploy and publish the respective branches.

**Comment by rofe** [comment]
Can't you already do this with strains?

**Comment by tripodsan** [comment]
> Can't you already do this with strains?

only of all project code (especially the `helix-config.yaml`) lives on the same repository. otherwise a deploy/publish in repo A would overwrite the VCL config of a deploy/publish in repo B.

**Comment by trieloff** [comment]
I'd rather keep the simple 1:1 relationship between `helix-config.yaml` and Fastly Service configs. You can easily create multiple service configs for each project and deploy them separately, with different subdomains.

**Comment by tripodsan** [comment]
agreed.
