### ISSUE TITLE
Default Selector for Strains

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#55]
Instead of pushing the Selector Dispatch/Routing Logic down into the Pipeline as https://github.com/adobe/helix-pipeline/issues/169 suggests, we could simplify this by allowing each strain to have a default selector. This way, all request-based conditions can be used for routing to the correct selector/template without having to build an additional router script.

I've discussed this with @tripodsan, but would also like to hear @kptdobe's opinion.

**Comment by tripodsan** [comment]
closing won't fix as it doesn't apply to helix 3 anymore.
