### ISSUE TITLE
Document Google Docs integration

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#56]
See adobe/helix-pages#67

**Comment by souravsingh** [comment]
@rofe I am interested in taking a stab at the issue. Where do I start?

**Comment by rofe** [comment]
@souravsingh great! Where to start depends on your Helix exposure so far :)

If you're a beginner, I'd recommend going through https://helix-home-adobe.project-helix.page/README.html.

As for the Google Docs integration, I think https://github.com/adobe/helix-pages/issues/67 describes the flow quite well in the description. There's also a service, [helix-googledocs2md](https://github.com/adobe/helix-googledocs2md) which is being used in the delivery process.

**Comment by rofe** [comment]
More about how to get started with Helix Pages: https://github.com/adobe/helix-example-basic

**Comment by rofe** [comment]
See https://github.com/adobe/helix-pages/issues/995
