### ISSUE TITLE
Move trieloff/helix-index-tree to adobe

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#65]
Create a new repository with the name `helix-index-tree`

- [x] Use [`helix-library`](https://github.com/adobe/helix-library) or [`helix-service`](https://github.com/adobe/helix-service) template
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [x] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [x] Update the repository `README.md` (search for `adobe/helix-service` or `adobe/helix-library`)
- [x] Update the `statuspage` and `newrelic` config in `package.json`: decide if your service falls under Development, Publishing or Delivery. See https://status.project-helix.io for reference.
- [x] Set up [Project Bot]
  - [x] Add a [`.github/org-project-bot.yaml`](https://github.com/adobe/helix-cli/blob/master/.github/org-project-bot.yaml)
  - [x] Enable _OrgProjectBot_ under _Settings > Integrations & services_ or https://github.com/organizations/adobe/settings/installations/690408 (Adobe org admins only)
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
  - [x] Enable _Renovatebot_ under _Settings > Integrations & services_ or https://github.com/organizations/adobe/settings/installations/1325372 (Adobe org admins only)
- [x] Set up [LGTM](https://github.com/organizations/adobe/settings/installations/870657)
- [x] Set up [Commitlint](https://github.com/organizations/adobe/settings/installations/728398)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

**Comment by trieloff** [comment]
Still needs
- [ ] `WSK_AUTH` env var for CircleCI

**Comment by tripodsan** [comment]
done. still failing the monitor setup.
see https://github.com/adobe/helix-index-tree/issues/6
