### ISSUE TITLE
Move trieloff/helix-index-pipelines to adobe

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#68]
Create a new repository with the name `helix-index-pipelines`

- [x] Use [`helix-library`](https://github.com/adobe/helix-library) or [`helix-service`](https://github.com/adobe/helix-service) template
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [x] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [x] Update the repository `README.md` (search for `adobe/helix-service` or `adobe/helix-library`)
- [ ] Update the `statuspage` and `newrelic` config in `package.json`: decide if your service falls under Development, Publishing or Delivery. See https://status.project-helix.io for reference.
- [x] Set up [Project Bot]
  - [x] Add a [`.github/org-project-bot.yaml`](https://github.com/adobe/helix-cli/blob/master/.github/org-project-bot.yaml)
  - [x] Enable _OrgProjectBot_ under _Settings > Integrations & services_ or https://github.com/organizations/adobe/settings/installations/690408 (Adobe org admins only)
- [ ] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
  - [x] Enable _Renovatebot_ under _Settings > Integrations & services_ or https://github.com/organizations/adobe/settings/installations/1325372 (Adobe org admins only)
- [x] Set up [LGTM](https://github.com/organizations/adobe/settings/installations/870657)
- [x] Set up [Commitlint](https://github.com/organizations/adobe/settings/installations/728398)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

**Comment by trieloff** [comment]
@tripodsan we should discuss on the preferred way to deploy this. Should be use the `helix-pages` namespace or request a new namespace?

**Comment by tripodsan** [comment]
I suggest to have a new namespace, eg `helix-indexing` or `helix-index` so we can isolate the activation limits from the rest of the system.

as for the deployment, I would try to version the action packages and have a structure that that symlinks (sequences). eg:

```
$ hlx deploy --packageName=index-pipelines-v1.2.1
$ hlx deploy --packageName=index-pipelines-v1.2.2
...

```

```
/index-piplines-v1.2.1
   /html_json
   /md_json
/index-piplines-v1.2.2
   /html_json
   /md_json
/index-pipelines
  /html_json@v1 -> /index-pipelines-v1.2.2
  /html_json@latest -> /index-pipelines-v1.2.2
```

**Comment by trieloff** [comment]
Ok, I've requested a new namespace with generous rate limits.

**Comment by tripodsan** [comment]
@trieloff can you move this to the adobe org? I would like to start working on the deployments

**Comment by trieloff** [comment]
I'll do it this afternoon.

**Comment by trieloff** [comment]
Moved to Adobe org: https://github.com/adobe/helix-index-pipelines

Still required:

- [ ] `.circlecli/config.yaml` @tripodsan 
- [ ] CircleCI env vars @tripodsan 
- [ ] Statuspage and New Relic Config @rofe

**Comment by tripodsan** [comment]
created followup: https://github.com/adobe/helix-index-pipelines/issues/6
