### ISSUE TITLE
Create helix-monitoring repo

### ISSUE THREAD

**Issue by rofe** [adobe/helix-home#74]
Our monitoring code is currently spread across multiple Helix repos. We should consolidate it in its own dedicated library, so it can be evolved independent of helix-status, and reused without having helix-status as a dependency.

WIP: https://github.com/adobe/helix-ops

- [x] Use [`helix-library`](https://github.com/adobe/helix-library) or [`helix-service`](https://github.com/adobe/helix-service) template
- [x] Add topics to the repository, at least `helix`
- [x] Add the group "[Project Helix Admins](https://github.com/orgs/adobe/teams/project-helix-admins)" with *Admin* permissions to the list of collaborators
- [x] Add the group "[Project Helix Developers](https://github.com/orgs/adobe/teams/project-helix-developers)" with *Write* permissions to the list of collaborators (Project Helix Guests will be taken care of automatically) 
- [x] Upload a social media image (use [this Spark template](https://spark.adobe.com/post/7srrIXaQVTw67/))
- [x] Set the repository description
- [x] Update the repository `README.md` (search for "service" or "library" and replace with something more meaningful where appropriate)
- [x] Update the `package.json` (search for "service" or "library" and replace with something more meaningful where appropriate)
- [x] Uncomment and adjust the `helix-post-deploy/monitoring` command in `.circleci/config.yaml`: decide if your service falls under Development, Publishing or Delivery. (note: failures in the latter two categories will ping on-call engineers on weekends!) See https://status.project-helix.io for reference.
- [x] Set up [Project Bot]
  - [x] Add a [`.github/org-project-bot.yaml`](https://github.com/adobe/helix-cli/blob/master/.github/org-project-bot.yaml)
  - [x] Enable _OrgProjectBot_ under _Settings > Integrations & services_ or https://github.com/organizations/adobe/settings/installations/690408 (Adobe org admins only)
- [x] Set up [CircleCI](https://circleci.com/add-projects/gh/adobe)
  - [x] Enable _Renovatebot_ under _Settings > Integrations & services_ or https://github.com/organizations/adobe/settings/installations/1325372 (Adobe org admins only)
- [x] Set up [LGTM](https://github.com/organizations/adobe/settings/installations/870657)
- [x] Set up [Commitlint](https://github.com/organizations/adobe/settings/installations/728398)
- [x] Follow the project in Slack channel [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/)
> Open the [`#helix-noisy`](https://cq-dev.slack.com/archives/C9HH8J553/) Slack channel, then type `/github subscribe adobe/helix-…`

**Comment by rofe** [comment]
We are essentially talking about the following code:
- The [`statuspage`](https://github.com/adobe/helix-status/blob/master/src/statuspage.js) tool in `helix-status` which creates or reuses a Statuspage component and returns its email address
- The [`newrelic`](https://github.com/adobe/helix-status/blob/master/src/newrelic.js) tool in `helix-status` which creates or reuses New Relic monitors, alert policies and notification channels.
- The [adobe/helix-post-deploy](https://github.com/adobe/helix-continuous/tree/master/.circleci/orbs/helix-post-deploy) orb source in `helix-continuous` containing the monitoring command executed during the `semantic-release` CircleCI job. Its scope was originally meant to include a selection of post-deploy commands (hence the naming). It currently contains 3 commands which are used by all Helix services.

Separating the monitoring tools from the actual `helix-status` code isn't a problem. But in terms of the orb, a clean separation of monitoring related code would entail the creation of a new orb with just the monitoring command and reuse it in the orb above. Another solution would be to simply move the monitoring tools into `helix-continuous` and grouping everything monitoring related there instead of creating a new repo...

@kptdobe @tripodsan @trieloff  wdyt?

**Comment by trieloff** [comment]
I thought my 👍 on the original issue was indication enough, but I like the idea. High five! 🙌 ⬆️5️⃣

**Comment by tripodsan** [comment]
:-) I created https://github.com/adobe/helix-status/issues/97 before reading this.

**Comment by rofe** [comment]
@trieloff It wasn't a yes/no question in my last comment :)

**Comment by kptdobe** [comment]
I am not a fan of having one repo for everything single thing we do but one of the main issue is that there is only one `.circleci/config.yaml` per repo which somehow defines what the repo is about. `helix-continuous` is then about smoke testing our dev environment (+storing the corresponding orb definition), `helix-status` is then the runtime action code for the status.
From there, I can only see a new repository. So +1 for `helix-status`

**Comment by trieloff** [comment]
I would definitely create one repo for the orb. We might want to create one or two additional repos for the status page and new relic tools that come with it. After the initial set-up, the maintenance of an additional repo is relatively low, so I don't have concerns about having many repos.

**Comment by rofe** [comment]
Thanks for your comments. I think I'll start with moving the monitoring tools and helix-post-deploy orb to a new `helix-ops` repo - this will leave us with some flexibility to add more ops related tooling in the future, and extend the helix-post-deploy orb to invoke them.

**Comment by rofe** [comment]
Done.
