### ISSUE TITLE
Fastly-Auto-Auth

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#85]
## Overview

How do we validate that a request made to an action in Adobe I/O Runtime has been made by a particular Fastly Service Config that is under management by Project Helix?

## Details

With #75 we have a way of authenticating actions like helix-run-query or helix-perf against Fastly. The user must provide the Fastly Service Config ID and a Fastly Token, and the action will validate the token using the Fastly API. This ensures that the user calling the API effectively has engineer-like privileges in Fastly.

For some use cases, this is a too harsh requirement and we just want to validate that a request has been made by Fastly, using a particular Service Config that is managed by Project Helix (`helix-publish`). This includes:

- `helix-embed` so that we can provide a shared API token for an embedding service that we want to make available to our customers, consuming the `helix-embed` service from their Helix-managed domains, but not to everyone.
- `helix-run-query`, so that we can run queries like @MarquiseRosier's "top blog posts" query as visitors, without having each visitor to provide the Fastly credentials (which would be highly impractical) and without having to make every query world readable.

## Simple Solution

A simple solution would be to store the `HLX_FASTLY_TOKEN` and the `HLX_FASTLY_NAMESPACE` in the `secrets` write-only edge dictionary when running `helix-publish`. The VCL would be adjusted so that requests to services requiring authentication would pass the token to Adobe I/O Runtime, which would have a wrapper (likely #75) to validate the request.

A possible drawback of the solution is that the token could be used for unintended purposes if you manage to deploy an untrusted action that consumes the token.

## Complex Solution

We store `HLX_FASTLY_NAMESPACE` and a randomly generated `FASTLY_AUTO_AUTH_TOKEN` in the `secrets` store. When making a request to an authenticated action, Fastly passes following things to the action:

1. the `timestamp` of the request
2. the `HLX_FASTLY_NAMESPACE`
3. the URI of the originating request (including hostname) `orig_uri`
4. a hash of all of the above + the `FASTLY_AUTO_AUTH_TOKEN` (`tokenhash`)

In the action, following validation is performed:

1. if the timestamp is not within 60 seconds of `now()`, reject the request
2. make a request from the action to `orig_uri`, including `timestamp` and `tokenhash` as headers
3. expect a status 2xx, reject for 4xx and 5xx

In Fastly, we have a validation handler for requests containing the `Helix-Timestamp` and `Helix-Tokenhash` headers that will: concatenate `req.http.Helix-Timestamp`, `table.loopup("secrets", "HLX_FASTLY_NAMESPACE")`, `req.http.Hostname`, `req.uri` and calculate a hash using the same function as above. When both hashes match, return a status 200, else return a status 401.

**Comment by trieloff** [comment]
@tripodsan @koraa feedback appreciated.

**Comment by tripodsan** [comment]
(I would rename `HLX_FASTLY_NAMESPACE` to `HLX_FASTLY_SERVICEID` as we did in helix-cli to avoid confusion (https://github.com/adobe/helix-cli/blob/81b9892aafdfc2b80af8121302798539e2dae83b/src/yargs-fastly.js#L15) )

**Comment by tripodsan** [comment]
if `FASTLY_AUTO_AUTH_TOKEN` is sent to the action **AND** the validation `orig_uri` as well, then anyone can pretend that a request is coming from fastly.

either the validation URI, or the `FASTLY_AUTO_AUTH_TOKEN` must be secret to the action.

for example:
- instead of `FASTLY_AUTO_AUTH_TOKEN`, name it `FASTLY_SHARED_SECRET`
- during publish / deploy, a shared secret is generated and stored in the edge dict for that _package_ and as (package) param for the action package
- helix-dispatch also linked below the action package.
- fastly will create a signature of the payload using the `FASTLY_SHARED_SECRET` as key.
- the action validates if the payload is properly signed.

**Comment by tripodsan** [comment]
IMO a better option would be, if the fastly could use SSL client certificates that can be validated in runtime.

**Comment by trieloff** [comment]
I've been thinking about SSL client certificates, too. Fastly does support client certificates when making requests to the origin (we'd need to have different origins for authenticated and non-authenticated requests)

**Comment by trieloff** [comment]
Thinking about this a bit more, we might go the JWT route (building a JWT token in Fastly should be doable), and use this for a `FASTLY_SHARED_SECRET`

**Comment by tripodsan** [comment]
closing won't fix as it doesn't apply to helix 3 anymore.
