### ISSUE TITLE
Scalability concerns

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-home#87]
Creating here as a general architecture concern:

Some numbers:

- ` curl https://theblog--davidnuescheler.hlx.page/head.html` triggers 22 activations. This seems to be the number of activations for an atomic html page.
- `curl https://theblog--davidnuescheler.hlx.page/styles.css` triggers 14 activations.
- `curl https://theblog--davidnuescheler.hlx.page/ms/archive/posts/2020/52-weeks-of-productivity.html` seems to trigger 100+ activations (hard to measure, so many). The page is composed of:
   - head.html (22 act.)
   - header.html (22 act.)
   - footer.html (22 act.)
   - own html (22 act.)
   - styles.css (14 act.)
   - and maybe more

It is imprecise but reveal one main thing: one surfer hitting a page on helix-pages will trigger 100+ activations per page load.
While we can extend the maximum number of activations per minutes in the helix-pages namespace and assume the resources are cheap, this feels like something to worry about.

On the other side of the chain, we have the logs: `curl https://theblog--davidnuescheler.hlx.page/ms/archive/posts/2020/52-weeks-of-productivity.html` generates 200+ logs entries for a total of 180+ KB. We do not manage the storage and assume the resources are cheap, but this feels like something to worry about.

The most expensive exercise I have done recently is the indexing of the pages (280) in a folder. I then triggered 280 indexing requests in a short amount of time. Those indexing requests triggered: 
- 280 * 100 ~ 28k activations
- 280 * 180 KB ~ 50 Mo of logs

All of that in a really short amount of time.
This hit the Runtime limits thus I had to proceed per batch of 20 pages and wait 45s in between each batch. Also, as a developer, I was building the indexes thus I add to restart over and over for several folders. 
My rough estimate is that I index 10k pages in total in a day of work. Numbers become:
- 10k * 100 ~ 1 million activations
- 10k * 180 KB ~ 18 Go of logs

And I do not feel like this is a stress test of the system.

As a developer or as an author, if you use helix-pages, you make constant reloads of the pages thus you probably do not load 10k pages in a day but if you are multiple developers and authors working with it, I think you can quickly go there.
Those are terrific numbers.

@trieloff @tripodsan @koraa @rofe @davidnuescheler @stefan-guggisberg @dominique-pfister @MarquiseRosier WDYT ?

**Comment by trieloff** [comment]
Do you have a breakdown of the 22 activations for head.html? It's about twice as much as I'd assume.

**Comment by trieloff** [comment]
I'm not super concerned about the total number of activations, as I don't see the Runtime limit as a constraint (we can make the limit go up with a meeting), other than the number of chained activations (because each is adding latency and no meeting in the world is going to give our users more patience). 

I'm even less concerned about the log data because we can easily turn the volume down.

What worries me a bit is how we can add more robustness in case an activation is failing.

**Comment by koraa** [comment]
> I'm not super concerned about the total number of activations, as I don't see the Runtime limit as a constraint (we can make the limit go up with a meeting), other than the number of chained activations (because each is adding latency and no meeting in the world is going to give our users more patience).

To be honest, I do not think this is accurate. We are on a serverless infrastructure, but we are not on lambda. I am not under the impression adobe io has been built for the kind of load amplification we're putting on it.

I'd be interested in what kind of optimization parameters adobe io suggest. Is it really a good idea to produce a massive amount of activations per request? What is the overhead per started action?

**Comment by kptdobe** [comment]
> Do you have a breakdown of the 22 activations for head.html? It's about twice as much as I'd assume.

```
Activation: 'static@1.5.37' (e29134ec9559474a9134ec9559074ae7)
Activation: 'static@1.5.37' (41aa1dda34744bc7aa1dda3474ebc783)
Activation: 'hlx--static' (5ace4d979d264dbd8e4d979d263dbd15)
Activation: 'static@v1' (3f276605bdd742eba76605bdd7b2eb99)
Activation: 'hlx--static' (96186a51fa964815986a51fa96f8155d)
Activation: 'static@v1' (0c528055c7c74fbe928055c7c7bfbec0)
Activation: 'static@1.5.37' (04f23e26311d4efdb23e26311d4efd9b)
Activation: 'static@1.5.37' (885a4164d21a42f39a4164d21a62f3ff)
Activation: 'static@v1' (e4061ec8f5f6447c861ec8f5f6147cfe)
Activation: 'hlx--static' (a4cbd7de08af4df28bd7de08af4df239)
Activation: 'static@v1' (2ed99a4013ea4605999a4013ea0605a5)
Activation: 'hlx--static' (1d47c78a62c54d8387c78a62c5dd835f)
Activation: 'resolve-git-ref@1.5.27' (9efaa7776bfb47ddbaa7776bfb97ddfe)
Activation: 'resolve-git-ref@v1' (67ee3f5e53c04768ae3f5e53c097681b)
Activation: 'resolve-git-ref@1.5.27' (768446d556f6485f8446d556f6c85fd3)
Activation: 'resolve-git-ref@v1_link' (26143459a45b4734943459a45bb73412)
Activation: 'resolve-git-ref@v1_link' (36e7c9796c874965a7c9796c875965e7)
Activation: 'resolve-git-ref@v1' (b21517dd576a4adc9517dd576a7adc82)
Activation: 'dispatch@3.0.3' (b2e4b814a19c469ca4b814a19cf69cfc)
Activation: 'dispatch@v3' (9091751e5b0d490c91751e5b0d290c6b)
Activation: 'html' (7f4e1cc54dc24fde8e1cc54dc25fde5e)
```

**Comment by trieloff** [comment]
Ah, I didn't count the sequences as activations.

**Comment by kptdobe** [comment]
Yes and number of "real" activations might need to be divided by 2. It depends on the cost of a sequence, but I assume they do not start the full machinery and are "cheap".

**Comment by trieloff** [comment]
To be fair, most of our "real" activations are cheap, too. Our actions run with a high degree of concurrency, and run for a very short time (most of it waiting for IO), so runtime should be able to handle a couple thousand rendering activations per second on a single virtual machine.

**Comment by trieloff** [comment]
We could build a "sequential activation" mode in `helix-dispatch`, to reduce the number of activations, but I don't think this would be worth the effort or the price (in terms of latency)

**Comment by koraa** [comment]
Can we measure that? What actually is the cost of an invocation? Compared to launching a process for instance… (launching a process takes a couple of ms); 

Running an invocation definetely involves – at least – queueing in kafka, multiple tcp connections being established, data transmitted, closed again to transmit data to the same process (action invoking itself)…also of course whatever setup we perform on action invocation…

Each network roundtrip would be maybe around 1ms, but they would end up so one invocation might block for 10-20ms?

Since processing a request now takes longer, all the memory resource & file descriptors need to stay locked for longer…maybe for (t_high) 20-40ms instead of for (t_low) 10ms? So you need t_high/t_low extra memory…

I would be interested in starting a project to actually measure the impact extra invocations have!

**Comment by tripodsan** [comment]
also, there are a lot of unnecessary invocations, like requesting 404.html for the gazillions of time.
also note, that the actual action invocation might not be a problem, but for example executing the static concurrently, each activation still makes tcp requests (github, epsagon, coralogix) which are by default keep-alive and produce probably lingering sockets. especially, since the processes are long-lived. also, the ssh handshake is not for free, either.

- maybe adding a simple memory cache to dispatch for resolve-ref and the 404 statics could also remove some of the load.

**Comment by kptdobe** [comment]
It would be great to measure the number of requests made to render one page (and all the linked resources). It seems we are currently hitting the limit of maximum number of opened sockets when requesting only 10+ pages in parallel.

> I don't see the Runtime limit as a constraint (we can make the limit go up with a meeting)

Increasing an existing limit should be done by a conscious and well thought decision based on a precise understanding of the resources we are using and why we need so much and some more. Before increasing any limit, we should do everything possible first in our code to reduce resources consumption and stay under.
I do not think this is a good architecture pattern because there will always be a limit. At the moment, things break apart for a dozen of concurrent page accesses and we do not necessarily masterise why, I do not want to imagine what will happen for a hundred or a thousand of current requests.

**Comment by kptdobe** [comment]
Here are some stats for a browser opening https://theblog--adobe.hlx.page/ (no cache): 

- 200 logs entries (162 KB csv file on disk)
- 72 activations identified for now (may be more): 
  - 42 activations visible in Coralogix because actions log at least one entry
  - 32 other activations identified but invisible in Coralogix (action does not log anything or maybe missing Coralogix key)
- 8 urls requested (each triggers X visible activations):
  1. https://theblog--adobe.hlx.page/ (1 activation)
  2. https://theblog--adobe.hlx.page/favicon.ico (5 activations)
  3. https://theblog--adobe.hlx.page/footer.plain.html (7 activations)
  4. https://theblog--adobe.hlx.page/head.html (7 activations)
  5. https://theblog--adobe.hlx.page/header.plain.html (7 activations)
  6. https://theblog--adobe.hlx.page/hlx_fonts/pnv6nym.css (5 activations)
  7. https://theblog--adobe.hlx.page/scripts.js (5 activations)
  8. https://theblog--adobe.hlx.page/style.css (5 activations)

**Comment by kptdobe** [comment]
In the current state, it is hard to get a clear picture of what happens when a request comes in because:
- wsk activation list cannot be used (too many activations, not user friendly, impossible to follow activations chain...)
- Coralogix has only a partial view:
  - Coralogix key might be missing, especially at the project level
  - Code might not log anything, thus no trace coming in
- Epsagon: I really do not understand what can be done there! But I assume same than for Coralogix, if token is missing, no data there

Still looking at ways to get a full and clear picture.

**Comment by kptdobe** [comment]
Another complexity is to isolate the "real" activations from the sequences. `wsk activation list` gives a lot more than necessary (for the measurement purpose).

**Comment by tripodsan** [comment]
closing as fixed due to helix 3 :-)
