### ISSUE TITLE
Query-backed Pipelines

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#90]
IDEA IN PROGRESS
how to serve a sitemap.xml or RSS feed in Helix?
- items are just query results
- Rendering is a pipeline

How to define routing?
How to select query and index?

**Comment by trieloff** [comment]
After @davidnuescheler poured cold water over the idea of a new type of pipelines, I thought about the simplest way to implement a `sitemap.xml` that is powered by an Algolia index and came up with this solution:

1. create a `sitemap.xml` in the `helix-pages` repository, with following content:

```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <esi:include src="/cgi-bin/sitemap?page=1" />
  <esi:include src="/cgi-bin/sitemap?page=2" />
  <esi:include src="/cgi-bin/sitemap?page=3" />
  <esi:include src="/cgi-bin/sitemap?page=4" />
  <esi:include src="/cgi-bin/sitemap?page=5" />
  <esi:include src="/cgi-bin/sitemap?page=6" />
  <esi:include src="/cgi-bin/sitemap?page=7" />
  <esi:include src="/cgi-bin/sitemap?page=8" />
  <esi:include src="/cgi-bin/sitemap?page=9" />
  <esi:include src="/cgi-bin/sitemap?page=10" />
</urlset>
```

2. create a `/cgi-bin/sitemap.js` which will query Algolia, and output the correct XML for each `<url>` in the sitemap. It will use the `page` parameter to make sure that the response size doesn't exceed 1 MB. If there are no more responses, it will return an empty document.

**Comment by rofe** [comment]
Requires https://github.com/adobe/helix-publish/issues/88

**Comment by davidnuescheler** [comment]
https://support.google.com/webmasters/answer/75712?hl=en

**Comment by trieloff** [comment]
From https://www.sitemaps.org/protocol.html

> You can provide multiple Sitemap files, but each Sitemap file that you provide must have no more than 50,000 URLs and must be no larger than 50MB (52,428,800 bytes). If you would like, you may compress your Sitemap files using gzip to reduce your bandwidth requirement; however the sitemap file once uncompressed must be no larger than 50MB. If you want to list more than 50,000 URLs, you must create multiple Sitemap files.

That would be 50 ESI includes in a row

> If you do provide multiple Sitemaps, you should then list each Sitemap file in a Sitemap index file. Sitemap index files may not list more than 50,000 Sitemaps and must be no larger than 50MB (52,428,800 bytes) and can be compressed. You can have more than one Sitemap index file. The XML format of a Sitemap index file is very similar to the XML format of a Sitemap file.

I think we only need to build this once we exceed the limits mentioned in the first paragraph.

**Comment by trieloff** [comment]
Oliver from Algolia (don't have his GitHub username) pointed me to this: https://github.com/algolia/algolia-sitemap

**Comment by rofe** [comment]
Interesting. But I personally would prefer a dynamic solution over 
> a script that should be ran periodically to keep the sitemaps up to date

**Comment by trieloff** [comment]
Me too, but we might be able to just wrap it in a runtime function and run it on request (with generous caches)

**Comment by dominique-pfister** [comment]
@trieloff , I'm having  trouble following your instructions:
> create a sitemap.xml in the helix-pages repository, with following content:
If I request that page in my local env, I'll get a `no script for xml` log message and the `esi:include` don't get processed.

After discussion with @rofe , I started writing a OW Action, that will either return the top sitemap (containing the esi includes) or a sitemap fragment if a `page` parameter is present. Can you help me setting up that `sitemap.xml` endpoint? Thanks.

**Comment by trieloff** [comment]
Hi, the "no script for XML" error seems to be specific to the simulator, so I'd try in Runtime/Fastly first.

Having an action for the root sitemap doesn't sound like a good idea, because we don't have a way of mapping an arbitrary action to a specific URL (like sitemap.xml)

For an example of a cgi-bin action, take a look at my trieloff/helix-demo repository.

**Comment by dominique-pfister** [comment]
Hmm, still doesn't work: https://dpfister.helix-demo.xyz/sitemap.xml 🤔

**Comment by dominique-pfister** [comment]
Another problem is that `/cgi-bin/sitemap?page=1` gets redirected to `/cgi-bin/sitemap/?page=1` which searches for a inexistent script `cgi-bin-index.html`, although one named `cgi-bin-sitemap` exists.

**Comment by trieloff** [comment]
Try giving calling /cgi-bin/sitemap.xml - we expect a file ending, however the specific ending doesn’t matter.


https://dpfister.helix-demo.xyz/cgi-bin/sitemap.xml

**Comment by trieloff** [comment]
The first issue seems to be that ESI isn’t enabled in the Static delivery path. I’d look at either helix-dispatch not setting the X-ESI header or helix-publish where helix.vcl is ignoring it.

**Comment by dominique-pfister** [comment]
I'm progressing :-) Looking at the invocation of that cgi-bin script [via Fastly](https://dpfister.helix-demo.xyz/cgi-bin/sitemap.js?page=1) as compared to local dev, I see that some params are missing (e.g. `owner`, `repo`, `ref`). What do you think, @trieloff , shouldn't they be added in `hlx_type_cgi` in the VCL?

**Comment by dominique-pfister** [comment]
I found some code in [`helix-static`](https://github.com/adobe/helix-static/blob/312436dc74bf2fdbbc8fb0f68b986b3b716cd9b0/src/index.js#L145):
```
  if (headers['Content-Type'] && (
    isCSS(headers['Content-Type'])
    || isJavaScript(headers['Content-Type']))
  ) && content.toString().match(/<esi:include/)) {
    cacheheaders['X-ESI'] = true;
  }
```
Should there be an additional clause for `isXML`?

**Comment by dominique-pfister** [comment]
After having fixed the code in `helix-static` above, ESI still doesn't work, because there's a special case in [`hlx_fetch_static`](https://github.com/adobe/helix-publish/blob/09d6b1bb8aac88fba4fef0251f16f6e9bf2f677a/layouts/fastly/helix.vcl#L723), that returns `deliver` for responses having a header `X-Static: Raw/Static`, which happens to be the case for `sitemap.xml`.

**Comment by trieloff** [comment]
> What do you think, @trieloff , shouldn't they be added in hlx_type_cgi in the VCL?

I'm torn on this: on the one hand, I like the simplicity of the cgi-bin actions as they are right now, i.e. no risk of naming conflicts, you can just drop in existing OpenWhisk actions, etc. On the other hand, having owner, repo, ref, strain, etc. would be convenient. On the one hand again, you could just pass these parameters from the sitemap.xml script if you really need them. On the other hand again, we could pass them as HTTP headers, which would reduce the risk of collisions, but still make the info available.

**Comment by trieloff** [comment]
ESI for static stuff was first disabled entirely, then I added it for CSS and JS, which can be immutified. Enabling it in general is probably a good idea.

**Comment by tripodsan** [comment]
> In the other hand, having owner, repo, ref, strain, etc. would be convenient.

I think when developers add cgi-bins in the context of helix, they should assume that some variables they have for pre.js actions are available. otherwise he cgi-bin is pretty useless, if they can't configure any default parameters or _environment_ variables.

but I see you point. what about using: `__git_repo`, `__git_owner` and `__git_ref` as params?

**Comment by trieloff** [comment]
`__hlx_owner` etc. would make it consistent with the OpenWhisk naming patterns.

**Comment by dominique-pfister** [comment]
What vcl function(s) should I use for that information? E.g. for the `owner` should I use `hlx_owner` or `hlx_github_static_owner`?

**Comment by dominique-pfister** [comment]
Requires https://github.com/adobe/helix-publish/issues/312

**Comment by trieloff** [comment]
Hlx_owner. hlx_static_owner is the fallback, which we shouldn't provide for CGI

**Comment by dominique-pfister** [comment]
Requires: https://github.com/adobe/helix-pages/issues/118

**Comment by dominique-pfister** [comment]
All required features available.
