### ISSUE TITLE
Undeploying Actions

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#94]
## Overview

How to undeploy actions that have been compromised by security issues or tainted dependencies.

## Details

Inspired by https://github.com/adobe/helix-embed/pull/119 and https://product.hubspot.com/blog/backend-tooling:

Our current architecture is deploy-only. This means, that actions that have security issues stay deployed and pose a risk to users. The post above has an interesting draft of a solution:

> With so many services constantly being built and deployed, it's a challenge to keep track of what's currently deployed as well as what it depends on. To help manage this, we have an internal system called Overwatch. Overwatch stores metadata about all deployed services and their dependencies and lets you query against this data. You can ask questions like "which deployed services were built before timestamp X?" or "which deployed services depend on library Y version < Z?" Our build and deploy systems also integrate with Overwatch, which is a powerful integration that enables things like our "bad builds" feature. The way this works is that if you realize a particular commit in a library has a nasty bug, you can mark that build as "bad" in our build UI. Once you do that, our deploy system will prevent people from deploying anything that depends on the broken version of that library (and optionally notify teams via Slack if they've already deployed something using it).

## Proposed Actions

I'd build a three-part system to handling these issues:

1. we extend `wsk-builder` with a deployment auditing feature similar to Overwatch. For each deployment, we store the effective `package-lock.json` in a relational database (maybe Google BigQuery), so that we can find for each deployment, which dependencies are used and for each dependency, which deployments are affected by it
2. we provide an API (maybe a small UI) to flag code versions and dependencies as "tainted". The dependency flagging should be automated through Tidelift
3. we provide a `helix-is-undeployed` filter that works as a wrapper, which will for each action check the database to see if:
  - the code or dependencies of the deployment are tainted
  - there is a newer version deployed
  - if the user has explicitly allowed the invocation of tainted actions through the `X-Helix-Ouch: true` header (header name TBD)

That way, we can easily disable the regular execution of actions with tainted dependencies or code without having to break backwards compatibility. A tainted action should respond with a redirect to the newest non-tainted version. Users can also opt-in to use tainted versions through a Request header.

Because the validity of the action is evaluated at runtime, the deployments can stay immutable (no actual und-employment needed), but we have a good auditing of what is being deployed and reachable at any time.

/cc @rofe

**Comment by tripodsan** [comment]
good idea, but I don't like adding this functionality to wsk-builder (unless you want to make it super public). ideally this should be a feature of runtime :-)

maybe like this:
- reduce the package-lock.json to a list of non-dev packages. maybe even only list the modules that are acutally included. this can be done in the wsk-builder.
- include the list of packages as action annotation. if there is a size-limit, add it as json file to the action.zip
- after the action was deployed successfully, _trigger_ a scan of the new action. ideally, this should be done automatically by runtime, but can be a CI step.
- the scan will grab the annotation or download the action and extract the info file and the update the database.

the advantage would be:
- the information can be include with other build systems (hlx deploy, serverless)
- the information is grabbed from the source
- the scanner can run independently, enumerating all actions and sequences recursively and build a comprehensive database. this could then evolve to a really cool admin tool :-)

/cc @alexkli do you already have something similar?

**Comment by alexkli** [comment]
FWIW, we deploy our actions with every nui app deployment (the whole thing) into `v1`, `v2` etc. openwhisk packages. Then we have a `current/` symlink/package binding which we switch to the latest version or go back to an older package on rollback.

All actions including web actions are protected with credentials, so direct access via `adobeioruntime.net` urls is impossible. Access is only possible through Adobe API Gateway which sets the right credentials and goes to `current/*` for the few web actions we have (3).

I don’t really see a need to remove old actions with security issues, as they will never be called. We could remove the old version package, but the hard part will be to identify which version includes the broken npm library in question... Maybe we’ll eventually remove old packages anyway, where we know we are not going to rollback to them anymore.

**Comment by rofe** [comment]
> WIW, we deploy our actions with every nui app deployment (the whole thing) into v1, v2 etc. openwhisk packages. Then we have a current/ symlink/package binding which we switch to the latest version or go back to an older package on rollback.

@alexkli we do a similar thing in Helix: for example, a newly deployed action `helix-foo@1.7.2` will be available under `helix-foo@v1.7`, `helix-foo@v1` and `helix-foo@latest` to allow users to either pin either a certain major/minor version or use latest.

**Comment by rofe** [comment]
@trieloff To be honest, the solution you propose sounds over engineered.

It would end up duplicating information that is already stored elsewhere (e.g. the `package-lock.json` of deployed actions are stored in GH tags), add a new layer of complexity and introduce an error prone manual step to flag actions as tainted. Also, I don't think we should encourage users to execute specific tainted (or any out of date) actions, and even if they wanted to do so at their own risk, they can already do it today by calling it by its full version. 

There are however two related actions that spring to mind:
- We could become more diligent when it comes to GH security alerts and npm audits to make sure we promptly respond to threats.
- We should start thinking about tooling for automatic undeployment of any deployed but obsolete actions (e.g. old versions which haven't seen any invocations in x months, actions deployed during testing in CI with `@ci*` versions) as helix actions are already in the thousands today, rendering `wsk action list` unusable without the possibility to filter.

**Comment by trieloff** [comment]
@tripodsan I like the idea of doing this asynchronously, either through package annotations, or as @rofe suggested through the use of git tags. For CI-versions, we could just annotate with the git sha, which would be enough of an identifier.

@rofe fully agree on the automated undeploying of old `@ci` actions. The likelihood that they are used directly by people who aren't intentionally trying to hurt themselves is nil. On the other points, my agreement is less than full.

In my mind, atomic, immutable deployments are a good idea as they provide us with a very stable infrastructure and limit the blast radius of breakage.

For a consumer of one of our services there are three options:

1. use `@latest` – you'll always get all fixes, but you risk that the service provider breaks backwards compatibility
2. use `@v3` – you'll get fixes until the service provider moves to the next major version and then you are out of luck
3. use `@v3.1.1` – you are pinned to a specific version, with all the downsides and none of the upsides

What I'm trying to build is a mitigation strategy for the downsides of the `@v3`-approach: give consumers the ability to stay at a version, but be notified about the issues that may arise from staying with an old version. 

Based on this, a simplified alternative approach:

all `@v…` sequences will have a `helix-deprecation-check` action before the actual invocation. The check will use the git tag to validate the `package-lock.json` and warn the consumer through a response header and log a warning in coralogix (so that we can filter)

**Comment by tripodsan** [comment]
> Based on this, a simplified alternative approach:

it don't like the extra overhead of executing more actions which 99.9% of the cases don't need.
also, reading the package-lock seems like a big overhead. also, the modules specified in the package-lock might not all be included in the action. and where would you get the information from, which packages are deprecated?

Having a _database_ of all deployed actions, versions and packages is IMO a good thing to have. this also gives devops a good overview of what is happening where. eventually we could even donate this to runtime and integrate it into io console.

**Comment by trieloff** [comment]
> eventually we could even donate this to runtime and integrate it into io console.

I'd love to hear what @tysonnorris @ddragosd and @mcorlan think about this.

**Comment by tysonnorris** [comment]
I don't know if this is something that could surface in runtime directly, but possibly in console and the aio cli. It definitely sounds useful, just that runtime has no notion of items within an action etc.

**Comment by tysonnorris** [comment]
BTW from an action point of view, it may be useful to have a deprecation flag to signal that the action exists, but cannot be used. We have something similar to this for "kind" in openwhisk, and could extend that concept to action I think, although currently there is no help in determining what should be done now that the kind (or action) is no longer available for use. We could probably allow a deprecation message in that case, but I'm not sure the whole lifecycle workflow for the action that would be useful for your case. (does a user who is a developer see this message? or would it have to be programatic? etc)

**Comment by trieloff** [comment]
I guess a deprecation flag combined with a source parameter could be a good solution. The source parameter would allow scanning tools to inspect the constituent parts of the action (from git) and the deprecation flag would control the behavior.

There might be two levels: soft deprecation results in a warning, but can be overridden by the user, hard deprecation is an error that cant be overridden.

Then developers would get a dashboard or API that lists the most popular deprecated actions and who’s invoking them.

**Comment by tripodsan** [comment]
> The source parameter would allow scanning tools to inspect the constituent parts of the action (from git)

I would include the sources directly to the action. not all build systems are based on git, or can guarantee that the source information (let's call it manifest :-) is still available at a later time. the simplest is probably to include the `package-lock.json` or `shrinkwrap.json` as you suggested earlier. and/or provide a more precise list with the help of the bundler.

**Comment by tripodsan** [comment]
let's close this and eventually discus this again later.
