### ISSUE TITLE
Generic Query Execution in Helix

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-home#95]
## Overview

Continuation of the discussion from https://github.com/adobe/helix-cli/pull/1279#issuecomment-579323804

> I'll provide a suggestion for a generic fallback (that will work with Helix Pages, user-defined queries, and with query engines that require a Runtime action)

How to allow developers to define queries without having to touch the Fastly configuration, for instance because they are using `helix-pages`, which doesn't provide a Fastly configuration of their own.

## Details

The current implementation of https://github.com/adobe/helix-publish/pull/288 is very performant, but also quite inflexible. At time of deployment, a number of aliases under `/_query/<indexname>/<queryname>` will get populated that take our request parameters and statically configured options from `helix-index.yaml` and use them to populate a request to be forwarded to the Algolia API.

As @tripodsan pointed out, this does not give an attractive option of using this feature to `helix-pages` developers, because they might be able to define their own indexes, but they cannot define their own queries and have to rely on queries pre-defined in the `helix-pages/helix-index.yaml`, which might not cover their particular use cases.

## Proposed Actions

We modify `helix-publish`, so that all requests to `/query/*/*` that do not match any of the static queries will get forwarded to a new Runtime action, `helix-query-index` using the parameters `index` and `query` to specify the first and second wildcard as well as a property `parameters` which contains the remaining, sorted and encoded URL query string. It will also pass the `owner`, `repo`, `ref` parameters that have been determined during strain resolution.

`helix-query-index` will then:
1. fetch `helix-index.yaml` from the repository specified by `owner`, `repo`, and `ref`
2. find the matching configuration specified by `index` and `query`
3. create a new query URL using the parameters from the configuration and using the parsed request `parameters`
4. respond with a `307` redirect to the URL calculated in the step above

The `helix.vcl` will then handle the `307` redirect in a similar way to the Static redirect, i.e. `restart;` the request flow, fetch from Algolia and return the result.

This approach will result in additional runtime activations, and additional latency compared to the static queries, but it offsets this with additional flexibility. We might be able to offset some of this by having different cache timeouts for the `helix-query-index` function and the actual Algolia query, so that `helix-query-index` will only need to be re-executed when new query parameters are used, but the Algolia index will be queried each time, so that content updates are reflected immediately.

In addition, this approach gives us the ability to implement other, runtime-backed quasi-index backends, for instance we can imagine queries going against the Google BigQuery index (using `helix-run-query`) or even novel indexes, for instance ones based on MongoDB (as a service)

**Comment by tripodsan** [comment]
An alternative could be that users that wish to use _pre-defined_ queries, will get a new fastly service (similar to _theblog_) which acts a primary cache for helix-pages.Additionally it also defines the static queries mapping (and other site specifics). this services gets automatically updated by the helix bot that needs to be installed on the repository.

the bot also ensures cache flushing etc.

**Comment by trieloff** [comment]
I'm not the biggest fan of the approach you describe, mostly because it relies on the existence of an additional Fastly service:
- new Fastly services are hard to create, programmatically (I don't think there's an API for that)
- getting a new Fastly service manually is also hard for most users
- the most common reasons why we use the outer Fastly service (domain handling and longer caching) can be solved more elegantly inside the helix-pages service config

**Comment by tripodsan** [comment]
closing for now. parts have been implemented and parts are no longer required by helix 3.
